#### Step 1: Fetch Movie Data from API

In [1]:
import pandas as pd
import requests
import json

In [2]:
with open("../config/config.json") as config_file: #to load  the config file 
    config = json.load(config_file)

api_token = config["TMDB_API_KEY"] # retrieves the api key from the config file

headers = {
    "Authorization": f"Bearer {api_token}" # sets the authorization header with the api key
}

movie_ids = [0, 299534, 19995, 140607, 299536, 597, 135397,
            420818, 24428, 168259, 99861, 284054, 12445,
            181808, 330457, 351286, 109445, 321612, 260513]

movies_data = []

for movie_id in movie_ids:
    # API endpoint
    url = f"https://api.themoviedb.org/3/movie/{movie_id}"
    
    #sends GET request to the API endpoint with the authorization header for the movie with the given ID 
    response = requests.get(url, headers=headers)
    
    # Check if request was successful
    if response.status_code == 200:
        movies_data.append(response.json())
        print(f"Successfully fetched movie ID: {movie_id}")
    else:
        print(f"Failed to fetch movie ID: {movie_id}, Status code: {response.status_code}")

# Convert the list of movie data to a DataFrame
raw_movies_df = pd.DataFrame(movies_data)

# Save to CSV
raw_movies_df.to_csv("../data/raw/raw_tmdb_movies.csv", index=False)

Failed to fetch movie ID: 0, Status code: 404
Successfully fetched movie ID: 299534
Successfully fetched movie ID: 19995
Successfully fetched movie ID: 140607
Successfully fetched movie ID: 299536
Successfully fetched movie ID: 597
Successfully fetched movie ID: 135397
Successfully fetched movie ID: 420818
Successfully fetched movie ID: 24428
Successfully fetched movie ID: 168259
Successfully fetched movie ID: 99861
Successfully fetched movie ID: 284054
Successfully fetched movie ID: 12445
Successfully fetched movie ID: 181808
Successfully fetched movie ID: 330457
Successfully fetched movie ID: 351286
Successfully fetched movie ID: 109445
Successfully fetched movie ID: 321612
Successfully fetched movie ID: 260513

## Fetching Movie Credits Data

In [3]:
with open("../config/config.json") as config_file: #to load  the config file 
    config = json.load(config_file)

api_token = config["TMDB_API_KEY"] # retrieves the api key from the config file

headers = {
    "Authorization": f"Bearer {api_token}" # sets the authorization header with the api key
}

movie_ids = [299534, 19995, 140607, 299536, 597, 135397,
            420818, 24428, 168259, 99861, 284054, 12445,
            181808, 330457, 351286, 109445, 321612, 260513]

credits_data = []

for movie_id in movie_ids:
    # API endpoint
    url = f"https://api.themoviedb.org/3/movie/{movie_id}/credits?language=en-US"
    
    #sends GET request to the API endpoint with the authorization header for the movie with the given ID 
    response = requests.get(url, headers=headers)
    
    # Check if request was successful
    if response.status_code == 200:
        credits_data.append(response.json())
        print(f"Successfully fetched credits of movie ID: {movie_id}")
    else:
        print(f"Failed to credits of movie ID: {movie_id}, Status code: {response.status_code}")

# Convert the list of movie data to a DataFrame
credits_df = pd.DataFrame(credits_data)

# Save to CSV
credits_df.to_csv("../data/raw/tmdb_movies_credits.csv", index=False)

Successfully fetched credits of movie ID: 299534
Successfully fetched credits of movie ID: 19995
Successfully fetched credits of movie ID: 140607
Successfully fetched credits of movie ID: 299536
Successfully fetched credits of movie ID: 597
Successfully fetched credits of movie ID: 135397
Successfully fetched credits of movie ID: 420818
Successfully fetched credits of movie ID: 24428
Successfully fetched credits of movie ID: 168259
Successfully fetched credits of movie ID: 99861
Successfully fetched credits of movie ID: 284054
Successfully fetched credits of movie ID: 12445
Successfully fetched credits of movie ID: 181808
Successfully fetched credits of movie ID: 330457
Successfully fetched credits of movie ID: 351286
Successfully fetched credits of movie ID: 109445
Successfully fetched credits of movie ID: 321612
Successfully fetched credits of movie ID: 260513

## Fetching Reviews By Movie Id List

In [4]:
import pandas as pd
import requests
import json

# Load API token from config file
with open("../config/config.json") as config_file:  # to load the config file
    config = json.load(config_file)

api_token = config["TMDB_API_KEY"]  # retrieves the API key from the config file

headers = {
    "Authorization": f"Bearer {api_token}"  # sets the authorization header with the API key
}

movie_ids = [
    0, 299534, 19995, 140607, 299536, 597, 135397,
    420818, 24428, 168259, 99861, 284054, 12445,
    181808, 330457, 351286, 109445, 321612, 260513
]

reviews_data = []

for movie_id in movie_ids:
    # API endpoint for reviews
    url = f"https://api.themoviedb.org/3/movie/{movie_id}/reviews"
    
    # Sends GET request to the API endpoint with the authorization header
    response = requests.get(url, headers=headers)
    
    # Check if request was successful
    if response.status_code == 200:
        reviews = response.json().get("results", [])
        for review in reviews:
            review["movie_id"] = movie_id  # Add movie_id to the review data for reference
            reviews_data.append(review)
        print(f"Successfully fetched reviews for movie ID: {movie_id}")
    else:
        print(f"Failed to fetch reviews for movie ID: {movie_id}, Status code: {response.status_code}")

# Convert the list of reviews data to a DataFrame
reviews_df = pd.DataFrame(reviews_data)

# Save to CSV
reviews_df.to_csv("../data/raw/tmdb_movie_reviews.csv", index=False)

print("Reviews data saved to tmdb_movie_reviews.csv")

Failed to fetch reviews for movie ID: 0, Status code: 404
Successfully fetched reviews for movie ID: 299534
Successfully fetched reviews for movie ID: 19995
Successfully fetched reviews for movie ID: 140607
Successfully fetched reviews for movie ID: 299536
Successfully fetched reviews for movie ID: 597
Successfully fetched reviews for movie ID: 135397
Successfully fetched reviews for movie ID: 420818
Successfully fetched reviews for movie ID: 24428
Successfully fetched reviews for movie ID: 168259
Successfully fetched reviews for movie ID: 99861
Successfully fetched reviews for movie ID: 284054
Successfully fetched reviews for movie ID: 12445
Successfully fetched reviews for movie ID: 181808
Successfully fetched reviews for movie ID: 330457
Successfully fetched reviews for movie ID: 351286
Successfully fetched reviews for movie ID: 109445
Successfully fetched reviews for movie ID: 321612
Successfully fetched reviews for movie ID: 260513
Reviews data saved to tmdb_movie_reviews.csv

In [5]:
reviews_df

,author,author_details,content,created_at,id,updated_at,url,movie_id
0,garethmb,"{'name': '', 'username': 'garethmb', 'avatar_p...",The epic Marvel Saga that started over ten yea...,2019-04-23T22:40:39.757Z,5cbf94670e0a266b96fba5ef,2021-06-23T15:58:20.522Z,https://www.themoviedb.org/review/5cbf94670e0a...,299534
1,Gimly,"{'name': 'Gimly', 'username': 'Ruuz', 'avatar_...","Hey, so, just some really quick thoughts I wan...",2019-04-24T15:24:16.492Z,5cc07fa00e0a2615fdf464d3,2021-06-23T15:58:20.545Z,https://www.themoviedb.org/review/5cc07fa00e0a...,299534
2,Manuel São Bento,"{'name': 'Manuel São Bento', 'username': 'msbr...","If you enjoy reading my Spoiler-Free reviews, ...",2019-04-26T13:29:35.406Z,5cc307bfc3a36809ab86e2fd,2021-06-23T15:58:20.634Z,https://www.themoviedb.org/review/5cc307bfc3a3...,299534
3,heroman,"{'name': '', 'username': 'heroman', 'avatar_pa...",okay so if your like me you questioned this mo...,2019-04-28T14:07:45.890Z,5cc5b3b1c3a36849368181c9,2021-06-23T15:58:20.684Z,https://www.themoviedb.org/review/5cc5b3b1c3a3...,299534
4,courtlynn,"{'name': '', 'username': 'courtlynn', 'avatar_...",We waited till day 5 of release in theaters. T...,2019-05-02T11:02:23.563Z,5ccace3f0e0a262fb3fee8b3,2021-06-23T15:58:21.421Z,https://www.themoviedb.org/review/5ccace3f0e0a...,299534
...,...,...,...,...,...,...,...,...
194,CinemaSerf,"{'name': 'CinemaSerf', 'username': 'Geronimo19...","A little like ""Into the Woods"" (2014) this is ...",2024-07-20T10:22:22.576Z,669b8fde5c72099d54de97da,2024-07-20T10:22:22.683Z,https://www.themoviedb.org/review/669b8fde5c72...,321612
195,r96sk,"{'name': '', 'username': 'r96sk', 'avatar_path...",A good sequel.\r\n\r\n<em>'Incredibles 2'</em>...,2020-08-03T14:59:39.652Z,5f28265bdbbb420034e60f39,2021-06-23T15:58:41.981Z,https://www.themoviedb.org/review/5f28265bdbbb...,260513
196,Gimly,"{'name': 'Gimly', 'username': 'Ruuz', 'avatar_...",Doesn't hold a candle to the original _Incredi...,2020-08-12T06:21:10.363Z,5f338a56ef8b3200371408df,2021-06-23T15:58:42.481Z,https://www.themoviedb.org/review/5f338a56ef8b...,260513
197,GenerationofSwine,"{'name': '', 'username': 'GenerationofSwine', ...","Ok, I didn't actually see or even really hear ...",2023-01-14T00:18:34.565Z,63c1f4da17b5ef00820b47ac,2023-01-14T00:18:34.658Z,https://www.themoviedb.org/review/63c1f4da17b5...,260513
198,CinemaSerf,"{'name': 'CinemaSerf', 'username': 'Geronimo19...",Walt Disney always said he wanted to release h...,2023-06-10T07:04:30.675Z,6484207ec9dbf9013a06693d,2023-06-10T07:04:30.751Z,https://www.themoviedb.org/review/6484207ec9db...,260513

In [6]:
reviews_df=reviews_df.drop(columns=(['author_details', 'created_at', 'updated_at', 'url','content', 'author'])) 
reviews_df

                           id  movie_id
0    5cbf94670e0a266b96fba5ef    299534
1    5cc07fa00e0a2615fdf464d3    299534
2    5cc307bfc3a36809ab86e2fd    299534
3    5cc5b3b1c3a36849368181c9    299534
4    5ccace3f0e0a262fb3fee8b3    299534
..                        ...       ...
194  669b8fde5c72099d54de97da    321612
195  5f28265bdbbb420034e60f39    260513
196  5f338a56ef8b3200371408df    260513
197  63c1f4da17b5ef00820b47ac    260513
198  6484207ec9dbf9013a06693d    260513

[199 rows x 2 columns]

In [7]:
review_ids = reviews_df['id'].tolist()

In [8]:
# Group the DataFrame by 'movie_id' and count the number of reviews for each 'movie_id'
review_counts = reviews_df.groupby('movie_id').size().reset_index(name='review_count')

# Display the resulting DataFrame
review_counts

    movie_id  review_count
0        597             7
1      12445             3
2      19995             6
3      24428            20
4      99861            20
5     109445             7
6     135397            14
7     140607             8
8     168259             2
9     181808            16
10    260513             4
11    284054            20
12    299534            20
13    299536            20
14    321612             8
15    330457             9
16    351286            10
17    420818             5

## Retrieve the details of a movie or TV show review Using the review_ids

In [9]:
import json
import requests
import pandas as pd
import time

# Load the config file to get the API key
with open("../config/config.json") as config_file:
    config = json.load(config_file)

api_token = config["TMDB_API_KEY"]  # Retrieves the API key from the config file

headers = {
    "Authorization": f"Bearer {api_token}"  # Sets the authorization header with the API key
}

# List of review IDs from the provided data
review_ids = [
    '5cbf94670e0a266b96fba5ef', '5cc07fa00e0a2615fdf464d3', '5cc307bfc3a36809ab86e2fd',
    '5cc5b3b1c3a36849368181c9', '5ccace3f0e0a262fb3fee8b3', '5cd7cf4ec3a3681d16c096ba',
    '5ce3e58dc3a3683bd81e14bb', '5d1fb1e694d8a849843eb1e2', '5dc32f3f9d893900183425f3',
    '5dc38a0e99259c00157a95b0', '5dc393138d22fc00123d43d8', '5dc399489d89390015350e9e',
    '5dc56e676f8d950010c2e33d', '5dc579d59c24fc0018bebb24', '5de2a4e33faba000130a8805',
    '5e00e904d1a89300148c8561', '5e00ee5f65686e0015977731', '5e010230d1a89300198cee67',
    '5e011acd65686e001398cfc5', '5e0286340284200016b21b19', '5b6964e1925141404f0d1094',
    '5ea448e4bdc34c0020261327', '639d90b74f33ad008cffa3f4', '63b9db528c0a48008537eacc',
    '6580fc9134e15208450834b3', '665b794d23eddc5f70d7f4db', '5675fd7792514179e7003dc5',
    '569bd8d7c3a36858c800046d', '571db465c3a3683de2000122', '58d44f2fc3a368128901aa17',
    '5df9269f65686e00158a07b7', '5e09705300508a0017954ffb', '601b3e45ca0e17003e4d4847',
    '606a218b124c8d0078d3953e', '5adff809c3a3683daa00ad3d', '5ae02e1e0e0a26156900f6da',
    '5ae0a3d20e0a26156301455e', '5ae4205b0e0a266c71003206', '5ae77ce60e0a262b9700a2df',
    '5ae85089c3a368134801a38e', '5ae866939251410cdc016c31', '5b043a7a0e0a2623ec029554',
    '5b3a6dfcc3a36845b800feee', '5b72ec050e0a267ef11b5f8c', '5b97fa459251413c68000753',
    '5c8425420e0a26430a636548', '5e05aa094c1d9a0019dd7bca', '5e20f463397df000149688a3',
    '5e21db442811a10015a1eb92', '5e24a3f25ed8e900136086cd', '5e24ab72a894d600123a5194',
    '5e24b4a2a894d600123a5d05', '5e24bace1dcb770012ca1ac8', '5e24c482a894d600123a7538',
    '5424aaccc3a36808760043df', '62a08f2e12197e565ea45214', '63c6aa4f66ae4d0085cb704a',
    '63ef88b95cc11d0086123924', '650689effa27f4010c4a62ad', '676476c20c865f24891f6a2b',
    '67a7d88131001bec13c8c9af', '55910381c3a36807f900065d', '559238f89251415df80000aa',
    '5639d6cd9251416d5201312c', '56544b11c3a36850fa003fcc', '56daade3c3a3684cae001628',
    '577c151c9251411ea2001fab', '58c16e48c3a368265000a4ec', '58d554b19251411fd502e9fe',
    '5b960066925141431c02bd8a', '62a70a08eb14fa09dca0a6e8', '62ebe4a18566d2005a48a7d6',
    '6340c52c1b7c59007917fd61', '64a82e99957e6d00c5dd35f6', '66583c22dc8efee4671d18cb',
    '5d2ddc7d6a300b0011a469df', '5d31d3991d78f2000ee0b492', '5e073ed64c1d9a0015e16e4c',
    '5ea18295ea37e00023288361', '62dfa72a5aba320050d6e1a1', '4fce8f8819c29523880000de',
    '59f29e47c3a3687126003ccd', '5a657f809251410b2d030491', '5c8426f992514127631f9b36',
    '5cad1876c3a36812a018fc9c', '5d46cf540f2fbd7864efbe30', '5dc32f2f5aadc4001520e0dd',
    '5dc389f37d2bc100133d06df', '5dc3930799259c00157aa7cb', '5dc3993d470ead00138cf1ec',
    '5dc56e556f8d950013c2d977', '5dc579c56f8d950010c2f5c5', '5e00e8fb75110d0018d85d20',
    '5e00ee5565686e0013987f15', '5e0102250284200014af5898', '5e011ac665686e0018983449',
    '5e02862b26dac10012674852', '5e08f6e5a1c59d0018aac032', '5e091b9d5ff34e0013b9ce5f',
    '5e09b284383df20018b90384', '553ba24592514138a90067c6', '55d987a692514143f30041fb',
    '56351986c3a3681b59017d48', '5804e364c3a3686a3400000e', '5a66d16ec3a3680cfb006191',
    '5b1678d7c3a3685352018aad', '5c842655c3a3684e95db3e38', '5dc32f5299259c00187a12c4',
    '5dc389ff8d22fc00143d1db1', '5dc393227d2bc100133d151b', '5dc399569d89390013350f9f',
    '5dc56e74470ead00189063a7', '5dc579e46f8d950017c29a57', '5e00e910d1a89300198cbe02',
    '5e00ee6875110d0011d84af1', '5e01023d0284200019af5170', '5e011ad70284200016af7e51',
    '5e02863c26dac10012674860', '5e08fd574a2226001728f48c', '5e091e34a1c59d0018ab0aea',
    '5e09b6c91684f700159c39d1', '5e0e0c5468b1ea00187f406e', '5a844e0fc3a36862e100c22f',
    '5a87b8550e0a26535a047632', '5a8894ba0e0a2653db05d34f', '5a8dfdcf0e0a263e6e006d75',
    '5a93b14b0e0a2616c602de5e', '5ad008f6c3a36842e4004d4d', '5af0b71092514119a6000099',
    '5b0e0e66c3a368714d000179', '5b2039f8c3a36814900052f3', '5b804c62c3a3687e19012e25',
    '5bf85f999251415cc80f0b3e', '5c8425630e0a26430363757a', '5ca545850e0a261b89b4d296',
    '5f4d29e5202e1100361ce3b7', '5f5b56cfe93e950038823008', '600b51f7cc277c003f1425ea',
    '636dec40f14dad008399e519', '6378f021fab3fa007fbeee6c', '63c025d905a5330085a4746a',
    '63c2107f8efe7300c83fe486', '5d72222477c01f621d5b89e0', '5d74d60fc6006d0012485dbb',
    '669b8f2f9e335c8207099b89', '5a3d22cd0e0a264cbe2375e7', '5a43b0320e0a264f7704e83a',
    '5a45ab9b0e0a264f39076887', '5a4934a89251415c8f0013cb', '5a58d3870e0a2634ef00be10',
    '5a9595d30e0a262efb00036b', '5ab85289925141395e025996', '5ab8a28e925141395b02a32f',
    '5bf85e340e0a261ac208d94d', '5c15a5c8c3a36866cc370c2c', '5df9384c65686e00158a23de',
    '601ca3a91108a8003fc4d46f', '60bae3c58d2f8d0079606d31', '63c20b9117b5ef00a7fbad33',
    '665e0266e7907a34c3bc924e', '667933b7d0fe030963ee7bfc', '5dd831ab3faba00015f96deb',
    '5ddb52473faba00013ff93b2', '5ddcebbea80673001212bb00', '5e5ad12966ae4d001984cafb',
    '5e7d5a9e6c74b94ca5cac987', '5f238d40eea34d00373953a3', '5f4d33abfea0d700343bfbfa',
    '646544500f2ae100e2bb87b0', '6482b2b999259c01392a5452', '5b2d4c080e0a264aea001943',
    '5b9f08d3925141231900fa88', '5bdc66dac3a368403200f453', '5c4471ba9251412bebdded43',
    '5c961f6bc3a3682e5ff54f83', '5d86b0565a469000299b4892', '5f705744a6e2d200386b06e5',
    '62a70afe22af3e00a1b6cc6d', '62ece433d036b6005d35014f', '64a837dbf9253200ca3ada44',
    '535fe7c2c3a36830a9006c93', '54b1bf59c3a3682313000089', '5ddc0bc53faba0001500a759',
    '5e534a61a76ac50016a5ef87', '5f4cfa52223a8b0037af2261', '62e8c8197caa47005e86fb63',
    '6465239bd05a0300e2f52115', '58d04679c3a3682dcd0002c6', '58e3b31892514127f6020406',
    '594309d5c3a3686c0d01406e', '5958a657c3a36828e701d4dc', '5a50fd690e0a26027500c693',
    '63001ac1bb2602008459e561', '6448b73e7f2d4a04dd0b1c5f', '669b8fde5c72099d54de97da',
    '5f28265bdbbb420034e60f39', '5f338a56ef8b3200371408df', '63c1f4da17b5ef00820b47ac',
    '6484207ec9dbf9013a06693d'
]

reviews_data = []
failed_ids = []

# Counter for rate limiting
count = 0

for review_id in review_ids:
    # Add a delay every 40 requests to avoid hitting API rate limits
    if count > 0 and count % 40 == 0:
        print(f"Pausing for 10 seconds after {count} requests...")
        time.sleep(10)
    
    # API endpoint for reviews
    url = f"https://api.themoviedb.org/3/review/{review_id}"
    
    try:
        # Send GET request to the API endpoint with the authorization header
        response = requests.get(url, headers=headers)
        count += 1
        
        # Check if request was successful
        if response.status_code == 200:
            review_data = response.json()
            reviews_data.append(review_data)
            print(f"Successfully fetched review ID: {review_id} ({count}/{len(review_ids)})")
        else:
            failed_ids.append({"id": review_id, "status_code": response.status_code})
            print(f"Failed to fetch review ID: {review_id}, Status code: {response.status_code}")
    
    except Exception as e:
        failed_ids.append({"id": review_id, "error": str(e)})
        print(f"Error fetching review ID: {review_id}, Error: {e}")

# Convert the list of review data to a DataFrame
if reviews_data:
    reviews_df = pd.DataFrame(reviews_data)
    
    # Save to CSV
    reviews_df.to_csv("../data/raw/tmdb_reviews.csv", index=False)
    print(f"Saved {len(reviews_data)} reviews to CSV file")
    
    # Display basic info about the DataFrame
    print("\nDataFrame Info:")
    print(f"Number of reviews fetched: {len(reviews_data)}")
    print(f"Columns: {reviews_df.columns.tolist()}")
else:
    print("No reviews were successfully fetched.")

# Save failed IDs to a separate file for reference
if failed_ids:
    failed_df = pd.DataFrame(failed_ids)
    failed_df.to_csv("../data/raw/failed_review_ids.csv", index=False)
    print(f"Saved {len(failed_ids)} failed review IDs to CSV file")

Successfully fetched review ID: 5cbf94670e0a266b96fba5ef (1/199)
Successfully fetched review ID: 5cc07fa00e0a2615fdf464d3 (2/199)
Successfully fetched review ID: 5cc307bfc3a36809ab86e2fd (3/199)
Successfully fetched review ID: 5cc5b3b1c3a36849368181c9 (4/199)
Successfully fetched review ID: 5ccace3f0e0a262fb3fee8b3 (5/199)
Successfully fetched review ID: 5cd7cf4ec3a3681d16c096ba (6/199)
Successfully fetched review ID: 5ce3e58dc3a3683bd81e14bb (7/199)
Successfully fetched review ID: 5d1fb1e694d8a849843eb1e2 (8/199)
Successfully fetched review ID: 5dc32f3f9d893900183425f3 (9/199)
Successfully fetched review ID: 5dc38a0e99259c00157a95b0 (10/199)
Successfully fetched review ID: 5dc393138d22fc00123d43d8 (11/199)
Successfully fetched review ID: 5dc399489d89390015350e9e (12/199)
Successfully fetched review ID: 5dc56e676f8d950010c2e33d (13/199)
Successfully fetched review ID: 5dc579d59c24fc0018bebb24 (14/199)
Successfully fetched review ID: 5de2a4e33faba000130a8805 (15/199)
Successfully fetched review ID: 5e00e904d1a89300148c8561 (16/199)
Successfully fetched review ID: 5e00ee5f65686e0015977731 (17/199)
Successfully fetched review ID: 5e010230d1a89300198cee67 (18/199)
Successfully fetched review ID: 5e011acd65686e001398cfc5 (19/199)
Successfully fetched review ID: 5e0286340284200016b21b19 (20/199)
Successfully fetched review ID: 5b6964e1925141404f0d1094 (21/199)
Successfully fetched review ID: 5ea448e4bdc34c0020261327 (22/199)
Successfully fetched review ID: 639d90b74f33ad008cffa3f4 (23/199)
Successfully fetched review ID: 63b9db528c0a48008537eacc (24/199)
Successfully fetched review ID: 6580fc9134e15208450834b3 (25/199)
Successfully fetched review ID: 665b794d23eddc5f70d7f4db (26/199)
Successfully fetched review ID: 5675fd7792514179e7003dc5 (27/199)
Successfully fetched review ID: 569bd8d7c3a36858c800046d (28/199)
Successfully fetched review ID: 571db465c3a3683de2000122 (29/199)
Successfully fetched review ID: 58d44f2fc3a368128901aa17 (30/199)
Successfully fetched review ID: 5df9269f65686e00158a07b7 (31/199)
Successfully fetched review ID: 5e09705300508a0017954ffb (32/199)
Successfully fetched review ID: 601b3e45ca0e17003e4d4847 (33/199)
Successfully fetched review ID: 606a218b124c8d0078d3953e (34/199)
Successfully fetched review ID: 5adff809c3a3683daa00ad3d (35/199)
Successfully fetched review ID: 5ae02e1e0e0a26156900f6da (36/199)
Successfully fetched review ID: 5ae0a3d20e0a26156301455e (37/199)
Successfully fetched review ID: 5ae4205b0e0a266c71003206 (38/199)
Successfully fetched review ID: 5ae77ce60e0a262b9700a2df (39/199)
Successfully fetched review ID: 5ae85089c3a368134801a38e (40/199)
Pausing for 10 seconds after 40 requests...
Successfully fetched review ID: 5ae866939251410cdc016c31 (41/199)
Successfully fetched review ID: 5b043a7a0e0a2623ec029554 (42/199)
Successfully fetched review ID: 5b3a6dfcc3a36845b800feee (43/199)
Successfully fetched review ID: 5b72ec050e0a267ef11b5f8c (44/199)
Successfully fetched review ID: 5b97fa459251413c68000753 (45/199)
Successfully fetched review ID: 5c8425420e0a26430a636548 (46/199)
Successfully fetched review ID: 5e05aa094c1d9a0019dd7bca (47/199)
Successfully fetched review ID: 5e20f463397df000149688a3 (48/199)
Successfully fetched review ID: 5e21db442811a10015a1eb92 (49/199)
Successfully fetched review ID: 5e24a3f25ed8e900136086cd (50/199)
Successfully fetched review ID: 5e24ab72a894d600123a5194 (51/199)
Successfully fetched review ID: 5e24b4a2a894d600123a5d05 (52/199)
Successfully fetched review ID: 5e24bace1dcb770012ca1ac8 (53/199)
Successfully fetched review ID: 5e24c482a894d600123a7538 (54/199)
Successfully fetched review ID: 5424aaccc3a36808760043df (55/199)
Successfully fetched review ID: 62a08f2e12197e565ea45214 (56/199)
Successfully fetched review ID: 63c6aa4f66ae4d0085cb704a (57/199)
Successfully fetched review ID: 63ef88b95cc11d0086123924 (58/199)
Successfully fetched review ID: 650689effa27f4010c4a62ad (59/199)
Successfully fetched review ID: 676476c20c865f24891f6a2b (60/199)
Successfully fetched review ID: 67a7d88131001bec13c8c9af (61/199)
Successfully fetched review ID: 55910381c3a36807f900065d (62/199)
Successfully fetched review ID: 559238f89251415df80000aa (63/199)
Successfully fetched review ID: 5639d6cd9251416d5201312c (64/199)
Successfully fetched review ID: 56544b11c3a36850fa003fcc (65/199)
Successfully fetched review ID: 56daade3c3a3684cae001628 (66/199)
Successfully fetched review ID: 577c151c9251411ea2001fab (67/199)
Successfully fetched review ID: 58c16e48c3a368265000a4ec (68/199)
Successfully fetched review ID: 58d554b19251411fd502e9fe (69/199)
Successfully fetched review ID: 5b960066925141431c02bd8a (70/199)
Successfully fetched review ID: 62a70a08eb14fa09dca0a6e8 (71/199)
Successfully fetched review ID: 62ebe4a18566d2005a48a7d6 (72/199)
Successfully fetched review ID: 6340c52c1b7c59007917fd61 (73/199)
Successfully fetched review ID: 64a82e99957e6d00c5dd35f6 (74/199)
Successfully fetched review ID: 66583c22dc8efee4671d18cb (75/199)
Successfully fetched review ID: 5d2ddc7d6a300b0011a469df (76/199)
Successfully fetched review ID: 5d31d3991d78f2000ee0b492 (77/199)
Successfully fetched review ID: 5e073ed64c1d9a0015e16e4c (78/199)
Successfully fetched review ID: 5ea18295ea37e00023288361 (79/199)
Successfully fetched review ID: 62dfa72a5aba320050d6e1a1 (80/199)
Pausing for 10 seconds after 80 requests...
Successfully fetched review ID: 4fce8f8819c29523880000de (81/199)
Successfully fetched review ID: 59f29e47c3a3687126003ccd (82/199)
Successfully fetched review ID: 5a657f809251410b2d030491 (83/199)
Successfully fetched review ID: 5c8426f992514127631f9b36 (84/199)
Successfully fetched review ID: 5cad1876c3a36812a018fc9c (85/199)
Successfully fetched review ID: 5d46cf540f2fbd7864efbe30 (86/199)
Successfully fetched review ID: 5dc32f2f5aadc4001520e0dd (87/199)
Successfully fetched review ID: 5dc389f37d2bc100133d06df (88/199)
Failed to fetch review ID: 5dc3930799259c00157aa7cb, Status code: 404
Successfully fetched review ID: 5dc3993d470ead00138cf1ec (90/199)
Successfully fetched review ID: 5dc56e556f8d950013c2d977 (91/199)
Successfully fetched review ID: 5dc579c56f8d950010c2f5c5 (92/199)
Successfully fetched review ID: 5e00e8fb75110d0018d85d20 (93/199)
Successfully fetched review ID: 5e00ee5565686e0013987f15 (94/199)
Successfully fetched review ID: 5e0102250284200014af5898 (95/199)
Successfully fetched review ID: 5e011ac665686e0018983449 (96/199)
Successfully fetched review ID: 5e02862b26dac10012674852 (97/199)
Successfully fetched review ID: 5e08f6e5a1c59d0018aac032 (98/199)
Successfully fetched review ID: 5e091b9d5ff34e0013b9ce5f (99/199)
Successfully fetched review ID: 5e09b284383df20018b90384 (100/199)
Successfully fetched review ID: 553ba24592514138a90067c6 (101/199)
Successfully fetched review ID: 55d987a692514143f30041fb (102/199)
Successfully fetched review ID: 56351986c3a3681b59017d48 (103/199)
Successfully fetched review ID: 5804e364c3a3686a3400000e (104/199)
Successfully fetched review ID: 5a66d16ec3a3680cfb006191 (105/199)
Successfully fetched review ID: 5b1678d7c3a3685352018aad (106/199)
Successfully fetched review ID: 5c842655c3a3684e95db3e38 (107/199)
Successfully fetched review ID: 5dc32f5299259c00187a12c4 (108/199)
Successfully fetched review ID: 5dc389ff8d22fc00143d1db1 (109/199)
Successfully fetched review ID: 5dc393227d2bc100133d151b (110/199)
Successfully fetched review ID: 5dc399569d89390013350f9f (111/199)
Successfully fetched review ID: 5dc56e74470ead00189063a7 (112/199)
Successfully fetched review ID: 5dc579e46f8d950017c29a57 (113/199)
Successfully fetched review ID: 5e00e910d1a89300198cbe02 (114/199)
Successfully fetched review ID: 5e00ee6875110d0011d84af1 (115/199)
Successfully fetched review ID: 5e01023d0284200019af5170 (116/199)
Successfully fetched review ID: 5e011ad70284200016af7e51 (117/199)
Successfully fetched review ID: 5e02863c26dac10012674860 (118/199)
Successfully fetched review ID: 5e08fd574a2226001728f48c (119/199)
Successfully fetched review ID: 5e091e34a1c59d0018ab0aea (120/199)
Pausing for 10 seconds after 120 requests...
Successfully fetched review ID: 5e09b6c91684f700159c39d1 (121/199)
Successfully fetched review ID: 5e0e0c5468b1ea00187f406e (122/199)
Successfully fetched review ID: 5a844e0fc3a36862e100c22f (123/199)
Successfully fetched review ID: 5a87b8550e0a26535a047632 (124/199)
Successfully fetched review ID: 5a8894ba0e0a2653db05d34f (125/199)
Successfully fetched review ID: 5a8dfdcf0e0a263e6e006d75 (126/199)
Successfully fetched review ID: 5a93b14b0e0a2616c602de5e (127/199)
Successfully fetched review ID: 5ad008f6c3a36842e4004d4d (128/199)
Successfully fetched review ID: 5af0b71092514119a6000099 (129/199)
Successfully fetched review ID: 5b0e0e66c3a368714d000179 (130/199)
Successfully fetched review ID: 5b2039f8c3a36814900052f3 (131/199)
Successfully fetched review ID: 5b804c62c3a3687e19012e25 (132/199)
Successfully fetched review ID: 5bf85f999251415cc80f0b3e (133/199)
Successfully fetched review ID: 5c8425630e0a26430363757a (134/199)
Successfully fetched review ID: 5ca545850e0a261b89b4d296 (135/199)
Successfully fetched review ID: 5f4d29e5202e1100361ce3b7 (136/199)
Successfully fetched review ID: 5f5b56cfe93e950038823008 (137/199)
Successfully fetched review ID: 600b51f7cc277c003f1425ea (138/199)
Successfully fetched review ID: 636dec40f14dad008399e519 (139/199)
Successfully fetched review ID: 6378f021fab3fa007fbeee6c (140/199)
Successfully fetched review ID: 63c025d905a5330085a4746a (141/199)
Successfully fetched review ID: 63c2107f8efe7300c83fe486 (142/199)
Successfully fetched review ID: 5d72222477c01f621d5b89e0 (143/199)
Successfully fetched review ID: 5d74d60fc6006d0012485dbb (144/199)
Successfully fetched review ID: 669b8f2f9e335c8207099b89 (145/199)
Successfully fetched review ID: 5a3d22cd0e0a264cbe2375e7 (146/199)
Successfully fetched review ID: 5a43b0320e0a264f7704e83a (147/199)
Successfully fetched review ID: 5a45ab9b0e0a264f39076887 (148/199)
Successfully fetched review ID: 5a4934a89251415c8f0013cb (149/199)
Successfully fetched review ID: 5a58d3870e0a2634ef00be10 (150/199)
Successfully fetched review ID: 5a9595d30e0a262efb00036b (151/199)
Successfully fetched review ID: 5ab85289925141395e025996 (152/199)
Successfully fetched review ID: 5ab8a28e925141395b02a32f (153/199)
Successfully fetched review ID: 5bf85e340e0a261ac208d94d (154/199)
Successfully fetched review ID: 5c15a5c8c3a36866cc370c2c (155/199)
Successfully fetched review ID: 5df9384c65686e00158a23de (156/199)
Successfully fetched review ID: 601ca3a91108a8003fc4d46f (157/199)
Successfully fetched review ID: 60bae3c58d2f8d0079606d31 (158/199)
Successfully fetched review ID: 63c20b9117b5ef00a7fbad33 (159/199)
Successfully fetched review ID: 665e0266e7907a34c3bc924e (160/199)
Pausing for 10 seconds after 160 requests...
Successfully fetched review ID: 667933b7d0fe030963ee7bfc (161/199)
Successfully fetched review ID: 5dd831ab3faba00015f96deb (162/199)
Successfully fetched review ID: 5ddb52473faba00013ff93b2 (163/199)
Successfully fetched review ID: 5ddcebbea80673001212bb00 (164/199)
Successfully fetched review ID: 5e5ad12966ae4d001984cafb (165/199)
Successfully fetched review ID: 5e7d5a9e6c74b94ca5cac987 (166/199)
Successfully fetched review ID: 5f238d40eea34d00373953a3 (167/199)
Successfully fetched review ID: 5f4d33abfea0d700343bfbfa (168/199)
Successfully fetched review ID: 646544500f2ae100e2bb87b0 (169/199)
Successfully fetched review ID: 6482b2b999259c01392a5452 (170/199)
Successfully fetched review ID: 5b2d4c080e0a264aea001943 (171/199)
Successfully fetched review ID: 5b9f08d3925141231900fa88 (172/199)
Successfully fetched review ID: 5bdc66dac3a368403200f453 (173/199)
Successfully fetched review ID: 5c4471ba9251412bebdded43 (174/199)
Successfully fetched review ID: 5c961f6bc3a3682e5ff54f83 (175/199)
Successfully fetched review ID: 5d86b0565a469000299b4892 (176/199)
Successfully fetched review ID: 5f705744a6e2d200386b06e5 (177/199)
Successfully fetched review ID: 62a70afe22af3e00a1b6cc6d (178/199)
Successfully fetched review ID: 62ece433d036b6005d35014f (179/199)
Successfully fetched review ID: 64a837dbf9253200ca3ada44 (180/199)
Successfully fetched review ID: 535fe7c2c3a36830a9006c93 (181/199)
Successfully fetched review ID: 54b1bf59c3a3682313000089 (182/199)
Successfully fetched review ID: 5ddc0bc53faba0001500a759 (183/199)
Successfully fetched review ID: 5e534a61a76ac50016a5ef87 (184/199)
Successfully fetched review ID: 5f4cfa52223a8b0037af2261 (185/199)
Successfully fetched review ID: 62e8c8197caa47005e86fb63 (186/199)
Successfully fetched review ID: 6465239bd05a0300e2f52115 (187/199)
Successfully fetched review ID: 58d04679c3a3682dcd0002c6 (188/199)
Successfully fetched review ID: 58e3b31892514127f6020406 (189/199)
Successfully fetched review ID: 594309d5c3a3686c0d01406e (190/199)
Successfully fetched review ID: 5958a657c3a36828e701d4dc (191/199)
Successfully fetched review ID: 5a50fd690e0a26027500c693 (192/199)
Successfully fetched review ID: 63001ac1bb2602008459e561 (193/199)
Successfully fetched review ID: 6448b73e7f2d4a04dd0b1c5f (194/199)
Successfully fetched review ID: 669b8fde5c72099d54de97da (195/199)
Successfully fetched review ID: 5f28265bdbbb420034e60f39 (196/199)
Successfully fetched review ID: 5f338a56ef8b3200371408df (197/199)
Successfully fetched review ID: 63c1f4da17b5ef00820b47ac (198/199)
Successfully fetched review ID: 6484207ec9dbf9013a06693d (199/199)
Saved 198 reviews to CSV file

DataFrame Info:
Number of reviews fetched: 198
Columns: ['id', 'author', 'author_details', 'content', 'created_at', 'iso_639_1', 'media_id', 'media_title', 'media_type', 'updated_at', 'url']
Saved 1 failed review IDs to CSV file

In [10]:
reviews_df

,id,author,author_details,content,created_at,iso_639_1,media_id,media_title,media_type,updated_at,url
0,5cbf94670e0a266b96fba5ef,garethmb,"{'name': '', 'username': 'garethmb', 'avatar_p...",The epic Marvel Saga that started over ten yea...,2019-04-23T22:40:39.757Z,en,299534,Avengers: Endgame,movie,2021-06-23T15:58:20.522Z,https://www.themoviedb.org/review/5cbf94670e0a...
1,5cc07fa00e0a2615fdf464d3,Gimly,"{'name': 'Gimly', 'username': 'Ruuz', 'avatar_...","Hey, so, just some really quick thoughts I wan...",2019-04-24T15:24:16.492Z,en,299534,Avengers: Endgame,movie,2021-06-23T15:58:20.545Z,https://www.themoviedb.org/review/5cc07fa00e0a...
2,5cc307bfc3a36809ab86e2fd,Manuel São Bento,"{'name': 'Manuel São Bento', 'username': 'msbr...","If you enjoy reading my Spoiler-Free reviews, ...",2019-04-26T13:29:35.406Z,en,299534,Avengers: Endgame,movie,2021-06-23T15:58:20.634Z,https://www.themoviedb.org/review/5cc307bfc3a3...
3,5cc5b3b1c3a36849368181c9,heroman,"{'name': '', 'username': 'heroman', 'avatar_pa...",okay so if your like me you questioned this mo...,2019-04-28T14:07:45.890Z,en,299534,Avengers: Endgame,movie,2021-06-23T15:58:20.684Z,https://www.themoviedb.org/review/5cc5b3b1c3a3...
4,5ccace3f0e0a262fb3fee8b3,courtlynn,"{'name': '', 'username': 'courtlynn', 'avatar_...",We waited till day 5 of release in theaters. T...,2019-05-02T11:02:23.563Z,en,299534,Avengers: Endgame,movie,2021-06-23T15:58:21.421Z,https://www.themoviedb.org/review/5ccace3f0e0a...
...,...,...,...,...,...,...,...,...,...,...,...
193,669b8fde5c72099d54de97da,CinemaSerf,"{'name': 'CinemaSerf', 'username': 'Geronimo19...","A little like ""Into the Woods"" (2014) this is ...",2024-07-20T10:22:22.576Z,en,321612,Beauty and the Beast,movie,2024-07-20T10:22:22.683Z,https://www.themoviedb.org/review/669b8fde5c72...
194,5f28265bdbbb420034e60f39,r96sk,"{'name': '', 'username': 'r96sk', 'avatar_path...",A good sequel.\r\n\r\n<em>'Incredibles 2'</em>...,2020-08-03T14:59:39.652Z,en,260513,Incredibles 2,movie,2021-06-23T15:58:41.981Z,https://www.themoviedb.org/review/5f28265bdbbb...
195,5f338a56ef8b3200371408df,Gimly,"{'name': 'Gimly', 'username': 'Ruuz', 'avatar_...",Doesn't hold a candle to the original _Incredi...,2020-08-12T06:21:10.363Z,en,260513,Incredibles 2,movie,2021-06-23T15:58:42.481Z,https://www.themoviedb.org/review/5f338a56ef8b...
196,63c1f4da17b5ef00820b47ac,GenerationofSwine,"{'name': '', 'username': 'GenerationofSwine', ...","Ok, I didn't actually see or even really hear ...",2023-01-14T00:18:34.565Z,en,260513,Incredibles 2,movie,2023-01-14T00:18:34.658Z,https://www.themoviedb.org/review/63c1f4da17b5...
197,6484207ec9dbf9013a06693d,CinemaSerf,"{'name': 'CinemaSerf', 'username': 'Geronimo19...",Walt Disney always said he wanted to release h...,2023-06-10T07:04:30.675Z,en,260513,Incredibles 2,movie,2023-06-10T07:04:30.751Z,https://www.themoviedb.org/review/6484207ec9db...

In [11]:
def eval_json(df, separator="|", key=None, column_key_map=None):
   
    default_key = key if key is not None else 'name'
   
    if column_key_map is None:
        column_key_map = {}
  
    result_df = df.copy()
   
    list_dict_columns = []
    single_dict_columns = []
   
    sample_size = min(1000, len(df))
    sample_df = df.head(sample_size)
    
    for column in df.columns:
        has_list_dicts = False
        has_single_dicts = False
        
        for val in sample_df[column].dropna():
            if isinstance(val, list) and val and all(isinstance(i, dict) for i in val if i is not None):
                has_list_dicts = True
                break
            elif isinstance(val, dict):
                has_single_dicts = True
                break
       
        if has_list_dicts:
            list_dict_columns.append(column)
        elif has_single_dicts:
            single_dict_columns.append(column)
    
    for column in list_dict_columns:
        column_key = column_key_map.get(column, default_key)
        def extract_values(x):
            if isinstance(x, list) and x:
                return separator.join(item.get(column_key, '') for item in x if isinstance(item, dict))
            return None
        result_df[column] = df[column].map(extract_values, na_action='ignore')
    
    for column in single_dict_columns:
        column_key = column_key_map.get(column, default_key)
        result_df[column] = df[column].map(
            lambda x: x.get(column_key, '') if isinstance(x, dict) else None,
            na_action='ignore'
        )
    return result_df

In [12]:
eval_ratings=eval_json(reviews_df, separator="|", key='rating', column_key_map=None)
eval_ratings

,id,author,author_details,content,created_at,iso_639_1,media_id,media_title,media_type,updated_at,url
0,5cbf94670e0a266b96fba5ef,garethmb,NaN,The epic Marvel Saga that started over ten yea...,2019-04-23T22:40:39.757Z,en,299534,Avengers: Endgame,movie,2021-06-23T15:58:20.522Z,https://www.themoviedb.org/review/5cbf94670e0a...
1,5cc07fa00e0a2615fdf464d3,Gimly,9.0,"Hey, so, just some really quick thoughts I wan...",2019-04-24T15:24:16.492Z,en,299534,Avengers: Endgame,movie,2021-06-23T15:58:20.545Z,https://www.themoviedb.org/review/5cc07fa00e0a...
2,5cc307bfc3a36809ab86e2fd,Manuel São Bento,10.0,"If you enjoy reading my Spoiler-Free reviews, ...",2019-04-26T13:29:35.406Z,en,299534,Avengers: Endgame,movie,2021-06-23T15:58:20.634Z,https://www.themoviedb.org/review/5cc307bfc3a3...
3,5cc5b3b1c3a36849368181c9,heroman,10.0,okay so if your like me you questioned this mo...,2019-04-28T14:07:45.890Z,en,299534,Avengers: Endgame,movie,2021-06-23T15:58:20.684Z,https://www.themoviedb.org/review/5cc5b3b1c3a3...
4,5ccace3f0e0a262fb3fee8b3,courtlynn,NaN,We waited till day 5 of release in theaters. T...,2019-05-02T11:02:23.563Z,en,299534,Avengers: Endgame,movie,2021-06-23T15:58:21.421Z,https://www.themoviedb.org/review/5ccace3f0e0a...
...,...,...,...,...,...,...,...,...,...,...,...
193,669b8fde5c72099d54de97da,CinemaSerf,6.0,"A little like ""Into the Woods"" (2014) this is ...",2024-07-20T10:22:22.576Z,en,321612,Beauty and the Beast,movie,2024-07-20T10:22:22.683Z,https://www.themoviedb.org/review/669b8fde5c72...
194,5f28265bdbbb420034e60f39,r96sk,7.0,A good sequel.\r\n\r\n<em>'Incredibles 2'</em>...,2020-08-03T14:59:39.652Z,en,260513,Incredibles 2,movie,2021-06-23T15:58:41.981Z,https://www.themoviedb.org/review/5f28265bdbbb...
195,5f338a56ef8b3200371408df,Gimly,6.0,Doesn't hold a candle to the original _Incredi...,2020-08-12T06:21:10.363Z,en,260513,Incredibles 2,movie,2021-06-23T15:58:42.481Z,https://www.themoviedb.org/review/5f338a56ef8b...
196,63c1f4da17b5ef00820b47ac,GenerationofSwine,10.0,"Ok, I didn't actually see or even really hear ...",2023-01-14T00:18:34.565Z,en,260513,Incredibles 2,movie,2023-01-14T00:18:34.658Z,https://www.themoviedb.org/review/63c1f4da17b5...
197,6484207ec9dbf9013a06693d,CinemaSerf,6.0,Walt Disney always said he wanted to release h...,2023-06-10T07:04:30.675Z,en,260513,Incredibles 2,movie,2023-06-10T07:04:30.751Z,https://www.themoviedb.org/review/6484207ec9db...

In [13]:
grouped_eval_ratings = eval_ratings.groupby('media_id').size().reset_index(name='count')
grouped_eval_ratings

    media_id  count
0        597      7
1      12445      3
2      19995      6
3      24428     19
4      99861     20
5     109445      7
6     135397     14
7     140607      8
8     168259      2
9     181808     16
10    260513      4
11    284054     20
12    299534     20
13    299536     20
14    321612      8
15    330457      9
16    351286     10
17    420818      5

In [14]:
grouped_eval_ratings2 = eval_ratings.groupby('media_id')['author_details'].sum().reset_index(name='count')
grouped_eval_ratings2

    media_id  count
0        597   50.0
1      12445   24.0
2      19995   30.0
3      24428   42.5
4      99861   32.5
5     109445   41.0
6     135397   67.5
7     140607   43.0
8     168259    9.0
9     181808   73.0
10    260513   29.0
11    284054  120.0
12    299534   58.0
13    299536   83.5
14    321612   46.0
15    330457   59.0
16    351286   44.0
17    420818   24.0

In [15]:
grouped_eval_ratings2 = grouped_eval_ratings2.rename(columns={'count': 'sum'})
grouped_eval_ratings2

    media_id    sum
0        597   50.0
1      12445   24.0
2      19995   30.0
3      24428   42.5
4      99861   32.5
5     109445   41.0
6     135397   67.5
7     140607   43.0
8     168259    9.0
9     181808   73.0
10    260513   29.0
11    284054  120.0
12    299534   58.0
13    299536   83.5
14    321612   46.0
15    330457   59.0
16    351286   44.0
17    420818   24.0

In [16]:
ratings_df = pd.concat([grouped_eval_ratings, grouped_eval_ratings2], axis=1)
ratings_df

    media_id  count  media_id    sum
0        597      7       597   50.0
1      12445      3     12445   24.0
2      19995      6     19995   30.0
3      24428     19     24428   42.5
4      99861     20     99861   32.5
5     109445      7    109445   41.0
6     135397     14    135397   67.5
7     140607      8    140607   43.0
8     168259      2    168259    9.0
9     181808     16    181808   73.0
10    260513      4    260513   29.0
11    284054     20    284054  120.0
12    299534     20    299534   58.0
13    299536     20    299536   83.5
14    321612      8    321612   46.0
15    330457      9    330457   59.0
16    351286     10    351286   44.0
17    420818      5    420818   24.0

In [17]:
ratings_df=ratings_df.drop(columns=['media_id'])
ratings_df

    count    sum
0       7   50.0
1       3   24.0
2       6   30.0
3      19   42.5
4      20   32.5
5       7   41.0
6      14   67.5
7       8   43.0
8       2    9.0
9      16   73.0
10      4   29.0
11     20  120.0
12     20   58.0
13     20   83.5
14      8   46.0
15      9   59.0
16     10   44.0
17      5   24.0

In [18]:
ratings_df.to_csv('../data/processed/ratings_df.csv')