## Step 2: Data Cleaning and Preprocessing

In [1]:
import pandas as pd
import numpy as np
import requests
import json

In [2]:
with open("../config/config.json") as config_file: #to load  the config file 
    config = json.load(config_file)

api_token = config["TMDB_API_KEY"] # retrieves the api key from the config file

headers = {
    "Authorization": f"Bearer {api_token}" # sets the authorization header with the api key
}

movie_ids = [0, 299534, 19995, 140607, 299536, 597, 135397,
            420818, 24428, 168259, 99861, 284054, 12445,
            181808, 330457, 351286, 109445, 321612, 260513]

movies_data = []

for movie_id in movie_ids:
    # API endpoint
    url = f"https://api.themoviedb.org/3/movie/{movie_id}"
    
    #sends GET request to the API endpoint with the authorization header for the movie with the given ID 
    response = requests.get(url, headers=headers)
    
    # Check if request was successful
    if response.status_code == 200:
        movies_data.append(response.json())
        print(f"Successfully fetched movie ID: {movie_id}")
    else:
        print(f"Failed to fetch movie ID: {movie_id}, Status code: {response.status_code}")

# Convert the list of movie data to a DataFrame
raw_movies_df = pd.DataFrame(movies_data)

# Save to CSV
raw_movies_df.to_csv("../data/raw/raw_tmdb_movies.csv", index=False)

Failed to fetch movie ID: 0, Status code: 404
Successfully fetched movie ID: 299534
Successfully fetched movie ID: 19995
Successfully fetched movie ID: 140607
Successfully fetched movie ID: 299536
Successfully fetched movie ID: 597
Successfully fetched movie ID: 135397
Successfully fetched movie ID: 420818
Successfully fetched movie ID: 24428
Successfully fetched movie ID: 168259
Successfully fetched movie ID: 99861
Successfully fetched movie ID: 284054
Successfully fetched movie ID: 12445
Successfully fetched movie ID: 181808
Successfully fetched movie ID: 330457
Successfully fetched movie ID: 351286
Successfully fetched movie ID: 109445
Successfully fetched movie ID: 321612
Successfully fetched movie ID: 260513

In [3]:
processed_df = raw_movies_df
processed_df

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,origin_country,original_language,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.marvel.com/movies/avengers-endgame,299534,tt4154796,[US],en,...,2019-04-24,2799439100,181,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Avenge the fallen.,Avengers: Endgame,False,8.238,26206
1,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.avatar.com/movies/avatar,19995,tt0499549,[US],en,...,2009-12-15,2923706026,162,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Enter the world of Pandora.,Avatar,False,7.588,32112
2,False,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,[US],en,...,2015-12-15,2068223624,136,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Every generation has a story.,Star Wars: The Force Awakens,False,7.262,19665
3,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.marvel.com/movies/avengers-infinit...,299536,tt4154756,[US],en,...,2018-04-25,2052415039,149,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Destiny arrives all the same.,Avengers: Infinity War,False,8.236,30386
4,False,/sCzcYW9h55WcesOqA12cgEr9Exw.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",https://www.paramountmovies.com/movies/titanic,597,tt0120338,[US],en,...,1997-11-18,2264162353,194,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Nothing on Earth could come between them.,Titanic,False,7.905,25865
5,False,/aIGIYJTyOkEVUmEd3z5x6diYsFx.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.jurassicworld.com/,135397,tt0369610,[US],en,...,2015-06-06,1671537444,124,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is open.,Jurassic World,False,6.700,20623
6,False,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",https://movies.disney.com/the-lion-king-2019,420818,tt6105098,[US],en,...,2019-07-12,1662020819,118,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The king has returned.,The Lion King,False,7.109,10301
7,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.marvel.com/movies/the-avengers,24428,tt0848228,[US],en,...,2012-04-25,1518815515,143,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Some assembly required.,The Avengers,False,7.734,31505
8,False,/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",https://www.uphe.com/movies/furious-7,168259,tt2820852,[US],en,...,2015-04-01,1515400000,137,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Released,Vengeance hits home.,Furious 7,False,7.225,10760
9,False,/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",365000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.marvel.com/movies/avengers-age-of-...,99861,tt2395427,[US],en,...,2015-04-22,1405403694,141,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A new age has come.,Avengers: Age of Ultron,False,7.271,23345
10,False,/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.marvel.com/movies/black-panther,284054,tt1825683,[US],en,...,2018-02-13,1349926083,135,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Long live the king.,Black Panther,False,7.400,22488
11,False,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",https://www.warnerbros.com/movies/harry-potter...,12445,tt1201607,[GB],en,...,2011-07-12,1341511219,130,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,False,8.087,20935
12,False,/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",200000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.starwars.com/films/star-wars-episo...,181808,tt2527336,[US],en,...,2017-12-13,1332698830,152,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Darkness rises...and light to meet it.,Star Wars: The Last Jedi,False,6.779,15532
13,False,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",https://movies.disney.com/frozen-2,330457,tt4520988,[US],en,...,2019-11-20,1453683476,103,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The past is not what it seems.,Frozen II,False,7.250,9867
14,False,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.uphe.com/movies/jurassic-world-fal...,351286,tt4881806,[US],en,...,2018-06-06,1310466296,129,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is gone.,Jurassic World: Fallen Kingdom,False,6.538,12004
15,False,/u2bZhH3nTf0So0UIC1QxAqBvC07.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://movies.disney.com/frozen,109445,tt2294629,[US],en,...,2013-11-20,1274219009,102,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Only the act of true love will thaw a frozen h...,Frozen,False,7.200,16777
16,False,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,321612,tt2771200,[US],en,...,2017-03-16,1266115964,129,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Be our guest.,Beauty and the Beast,False,6.971,15584
17,False,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://movies.disney.com/incredibles-2,260513,tt3606756,[US],en,...,2018-06-14,1242805359,118,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,"It's been too long, dahlings.",Incredibles 2,False,7.454,13021

#### Drop irrelevant columns: ['adult', 'imdb_id', 'original_title', 'video', 'homepage'].

In [4]:
processed_df=processed_df.drop(columns=['adult', 'imdb_id', 'original_title', 'video', 'homepage'])
processed_df.to_csv("../data/processed/processed_df.csv", index=False)
processed_df.columns

Index(['backdrop_path', 'belongs_to_collection', 'budget', 'genres', 'id',
       'origin_country', 'original_language', 'overview', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'revenue', 'runtime', 'spoken_languages', 'status',
       'tagline', 'title', 'vote_average', 'vote_count'],
      dtype='object')

#### Evaluate JSON-like columns

In [5]:
json_df=processed_df[['belongs_to_collection', 'genres', 'production_countries',
'production_companies', 'spoken_languages']]
json_df.to_csv("../data/processed/json_df.csv", index=False)

In [6]:
json_df.columns

Index(['belongs_to_collection', 'genres', 'production_countries',
       'production_companies', 'spoken_languages'],
      dtype='object')

#### Custom Function to Evaluate JSON-like Data, Extract and Clean Key Data Points

In [7]:
def eval_json(df, separator="|", key=None, column_key_map=None):
   
    default_key = key if key is not None else 'name'
   
    if column_key_map is None:
        column_key_map = {}
  
    result_df = df.copy()
   
    list_dict_columns = []
    single_dict_columns = []
   
    sample_size = min(1000, len(df))
    sample_df = df.head(sample_size)
    
    for column in df.columns:
        has_list_dicts = False
        has_single_dicts = False
        
        for val in sample_df[column].dropna():
            if isinstance(val, list) and val and all(isinstance(i, dict) for i in val if i is not None):
                has_list_dicts = True
                break
            elif isinstance(val, dict):
                has_single_dicts = True
                break
       
        if has_list_dicts:
            list_dict_columns.append(column)
        elif has_single_dicts:
            single_dict_columns.append(column)
    
    for column in list_dict_columns:
        column_key = column_key_map.get(column, default_key)
        def extract_values(x):
            if isinstance(x, list) and x:
                return separator.join(item.get(column_key, '') for item in x if isinstance(item, dict))
            return None
        result_df[column] = df[column].map(extract_values, na_action='ignore')
    
    for column in single_dict_columns:
        column_key = column_key_map.get(column, default_key)
        result_df[column] = df[column].map(
            lambda x: x.get(column_key, '') if isinstance(x, dict) else None,
            na_action='ignore'
        )
    return result_df

In [8]:
# Process the JSON-like columns in the DataFrame
eval_json_df = eval_json(json_df)
eval_json_df

,belongs_to_collection,genres,production_countries,production_companies,spoken_languages
0,The Avengers Collection,Adventure|Science Fiction|Action,United States of America,Marvel Studios,English|日本語|
1,Avatar Collection,Action|Adventure|Fantasy|Science Fiction,United States of America|United Kingdom,Dune Entertainment|Lightstorm Entertainment|20...,English|Español
2,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.|Bad Robot,English
3,The Avengers Collection,Adventure|Action|Science Fiction,United States of America,Marvel Studios,English|
4,None,Drama|Romance,United States of America,Paramount Pictures|20th Century Fox|Lightstorm...,English|Français|Deutsch|svenska|Italiano|Pусский
5,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English
6,The Lion King (Reboot) Collection,Adventure|Drama|Family|Animation,United States of America,Walt Disney Pictures|Fairview Entertainment,English
7,The Avengers Collection,Science Fiction|Action|Adventure,United States of America,Marvel Studios,English|हिन्दी|Pусский
8,The Fast and the Furious Collection,Action|Thriller|Crime,United States of America,Original Film|One Race|Universal Pictures,العربية|English|Español|ภาษาไทย
9,The Avengers Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English
10,Black Panther Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English|한국어/조선말|Kiswahili|
11,Harry Potter Collection,Fantasy|Adventure,United Kingdom|United States of America,Warner Bros. Pictures|Heyday Films,English
12,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.,English
13,Frozen Collection,Family|Animation|Adventure|Comedy|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
14,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English|Pусский
15,Frozen Collection,Animation|Family|Adventure|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
16,None,Family|Fantasy|Romance,United States of America,Walt Disney Pictures|Mandeville Films,English|Français
17,The Incredibles Collection,Action|Adventure|Animation|Family,United States of America,Walt Disney Pictures|Pixar,English

#### 4. Inspect extracted columns using value_counts() to identify anomalies.

In [9]:
eval_json_df.value_counts()

belongs_to_collection                genres                                     production_countries                     production_companies                                                          spoken_languages
Avatar Collection                    Action|Adventure|Fantasy|Science Fiction   United States of America|United Kingdom  Dune Entertainment|Lightstorm Entertainment|20th Century Fox|Ingenious Media  English|Español                    1
Black Panther Collection             Action|Adventure|Science Fiction           United States of America                 Marvel Studios                                                                English|한국어/조선말|Kiswahili|         1
Frozen Collection                    Animation|Family|Adventure|Fantasy         United States of America                 Walt Disney Pictures|Walt Disney Animation Studios                            English                            1
                                     Family|Animation|Adventure|Comedy|Fantasy  United States of America                 Walt Disney Pictures|Walt Disney Animation Studios                            English                            1
Harry Potter Collection              Fantasy|Adventure                          United Kingdom|United States of America  Warner Bros. Pictures|Heyday Films                                            English                            1
Jurassic Park Collection             Action|Adventure|Science Fiction|Thriller  United States of America                 Amblin Entertainment|Universal Pictures                                       English                            1
                                                                                                                                                                                                       English|Pусский                    1
Star Wars Collection                 Adventure|Action|Science Fiction           United States of America                 Lucasfilm Ltd.                                                                English                            1
                                                                                                                         Lucasfilm Ltd.|Bad Robot                                                      English                            1
The Avengers Collection              Action|Adventure|Science Fiction           United States of America                 Marvel Studios                                                                English                            1
                                     Adventure|Action|Science Fiction           United States of America                 Marvel Studios                                                                English|                           1
                                     Adventure|Science Fiction|Action           United States of America                 Marvel Studios                                                                English|日本語|                       1
                                     Science Fiction|Action|Adventure           United States of America                 Marvel Studios                                                                English|हिन्दी|Pусский             1
The Fast and the Furious Collection  Action|Thriller|Crime                      United States of America                 Original Film|One Race|Universal Pictures                                     العربية|English|Español|ภาษาไทย    1
The Incredibles Collection           Action|Adventure|Animation|Family          United States of America                 Walt Disney Pictures|Pixar                                                    English                            1
The Lion King (Reboot) Collection    Adventure|Drama|Family|Animation           United States of America                 Walt Disney Pictures|Fairview Entertainment                                   English                            1
Name: count, dtype: int64

In [10]:
processed_df=processed_df.drop(columns=['belongs_to_collection', 'genres', 'production_countries',
'production_companies', 'spoken_languages'])
movie_df=pd.concat([processed_df, eval_json_df], axis=1)
movie_df

,backdrop_path,budget,id,origin_country,original_language,overview,popularity,poster_path,release_date,revenue,...,status,tagline,title,vote_average,vote_count,belongs_to_collection,genres,production_countries,production_companies,spoken_languages
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,356000000,299534,[US],en,After the devastating events of Avengers: Infi...,22.2597,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,2019-04-24,2799439100,...,Released,Avenge the fallen.,Avengers: Endgame,8.238,26206,The Avengers Collection,Adventure|Science Fiction|Action,United States of America,Marvel Studios,English|日本語|
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,237000000,19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",31.3525,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,2009-12-15,2923706026,...,Released,Enter the world of Pandora.,Avatar,7.588,32112,Avatar Collection,Action|Adventure|Fantasy|Science Fiction,United States of America|United Kingdom,Dune Entertainment|Lightstorm Entertainment|20...,English|Español
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,245000000,140607,[US],en,Thirty years after defeating the Galactic Empi...,12.7841,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,2015-12-15,2068223624,...,Released,Every generation has a story.,Star Wars: The Force Awakens,7.262,19665,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.|Bad Robot,English
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,300000000,299536,[US],en,As the Avengers and their allies have continue...,32.6907,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,2018-04-25,2052415039,...,Released,Destiny arrives all the same.,Avengers: Infinity War,8.236,30386,The Avengers Collection,Adventure|Action|Science Fiction,United States of America,Marvel Studios,English|
4,/sCzcYW9h55WcesOqA12cgEr9Exw.jpg,200000000,597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,31.6333,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,1997-11-18,2264162353,...,Released,Nothing on Earth could come between them.,Titanic,7.905,25865,None,Drama|Romance,United States of America,Paramount Pictures|20th Century Fox|Lightstorm...,English|Français|Deutsch|svenska|Italiano|Pусский
5,/aIGIYJTyOkEVUmEd3z5x6diYsFx.jpg,150000000,135397,[US],en,Twenty-two years after the events of Jurassic ...,19.5099,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,2015-06-06,1671537444,...,Released,The park is open.,Jurassic World,6.700,20623,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,260000000,420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",22.2842,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,2019-07-12,1662020819,...,Released,The king has returned.,The Lion King,7.109,10301,The Lion King (Reboot) Collection,Adventure|Drama|Family|Animation,United States of America,Walt Disney Pictures|Fairview Entertainment,English
7,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,220000000,24428,[US],en,When an unexpected enemy emerges and threatens...,33.8215,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,2012-04-25,1518815515,...,Released,Some assembly required.,The Avengers,7.734,31505,The Avengers Collection,Science Fiction|Action|Adventure,United States of America,Marvel Studios,English|हिन्दी|Pусский
8,/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg,190000000,168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,14.2561,/wurKlC3VKUgcfsn0K51MJYEleS2.jpg,2015-04-01,1515400000,...,Released,Vengeance hits home.,Furious 7,7.225,10760,The Fast and the Furious Collection,Action|Thriller|Crime,United States of America,Original Film|One Race|Universal Pictures,العربية|English|Español|ภาษาไทย
9,/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg,365000000,99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,17.2051,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,2015-04-22,1405403694,...,Released,A new age has come.,Avengers: Age of Ultron,7.271,23345,The Avengers Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English
10,/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg,200000000,284054,[US],en,"King T'Challa returns home to the reclusive, t...",18.2929,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,2018-02-13,1349926083,...,Released,Long live the king.,Black Panther,7.400,22488,Black Panther Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English|한국어/조선말|Kiswahili|
11,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,125000000,12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",18.2595,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,2011-07-12,1341511219,...,Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.087,20935,Harry Potter Collection,Fantasy|Adventure,United Kingdom|United States of America,Warner Bros. Pictures|Heyday Films,English
12,/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg,200000000,181808,[US],en,Rey develops her newly discovered abilities wi...,13.8661,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,2017-12-13,1332698830,...,Released,Darkness rises...and light to meet it.,Star Wars: The Last Jedi,6.779,15532,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.,English
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,150000000,330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",11.1016,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,2019-11-20,1453683476,...,Released,The past is not what it seems.,Frozen II,7.250,9867,Frozen Collection,Family|Animation|Adventure|Comedy|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,170000000,351286,[US],en,Three years after Jurassic World was destroyed...,14.0844,/270MrJNqJovumHXGE6SSt0zwUIF.jpg,2018-06-06,1310466296,...,Released,The park is gone.,Jurassic World: Fallen Kingdom,6.538,12004,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English|Pусский
15,/u2bZhH3nTf0So0UIC1QxAqBvC07.jpg,150000000,109445,[US],en,Young princess Anna of Arendelle dreams about ...,20.7782,/m4uhSpErBKprhsclr0zynTYdupb.jpg,2013-11-20,1274219009,...,Released,Only the act of true love will thaw a frozen h...,Frozen,7.200,16777,Frozen Collection,Animation|Family|Adventure|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,160000000,321612,[US],en,A live-action adaptation of Disney's version o...,17.1086,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,2017-03-16,1266115964,...,Released,Be our guest.,Beauty and the Beast,6.971,15584,None,Family|Fantasy|Romance,United States of America,Walt Disney Pictures|Mandeville Films,English|Français
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,200000000,260513,[US],en,Elastigirl springs into action to save the day...,9.8992,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,2018-06-14,1242805359,...,Released,"It's been too long, dahlings.",Incredibles 2,7.454,13021,The Incredibles Collection,Action|Adventure|Animation|Family,United States of America,Walt Disney Pictures|Pixar,English

In [11]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   backdrop_path          18 non-null     object
 1   budget                 18 non-null     int64
 2   id                     18 non-null     int64
 3   origin_country         18 non-null     object
 4   original_language      18 non-null     object
 5   overview               18 non-null     object
 6   popularity             18 non-null     float64
 7   poster_path            18 non-null     object
 8   release_date           18 non-null     object
 9   revenue                18 non-null     int64
 10  runtime                18 non-null     int64
 11  status                 18 non-null     object
 12  tagline                18 non-null     object
 13  title                  18 non-null     object
 14  vote_average           18 non-null     float64
 15  vote_count             18 non-null     int64
 16  belongs_to_collection  16 non-null     object
 17  genres                 18 non-null     object
 18  production_countries   18 non-null     object
 19  production_companies   18 non-null     object
 20  spoken_languages       18 non-null     object
dtypes: float64(2), int64(5), object(14)
memory usage: 3.1+ KB

## Handling Missing & Incorrect Data

#### 5. Convert column datatypes:

In [12]:

movie_df['budget']=pd.to_numeric(movie_df['budget'], errors='coerce')
movie_df['id']=pd.to_numeric(movie_df['id'], errors='coerce')
movie_df['popularity']=pd.to_numeric(movie_df['popularity'], errors='coerce')
movie_df['vote_average']=pd.to_numeric(movie_df['vote_average'], errors='coerce')
movie_df['release_date']=pd.to_datetime(movie_df['release_date'], errors='coerce')

In [13]:
movie_df

,backdrop_path,budget,id,origin_country,original_language,overview,popularity,poster_path,release_date,revenue,...,status,tagline,title,vote_average,vote_count,belongs_to_collection,genres,production_countries,production_companies,spoken_languages
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,356000000,299534,[US],en,After the devastating events of Avengers: Infi...,22.2597,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,2019-04-24,2799439100,...,Released,Avenge the fallen.,Avengers: Endgame,8.238,26206,The Avengers Collection,Adventure|Science Fiction|Action,United States of America,Marvel Studios,English|日本語|
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,237000000,19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",31.3525,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,2009-12-15,2923706026,...,Released,Enter the world of Pandora.,Avatar,7.588,32112,Avatar Collection,Action|Adventure|Fantasy|Science Fiction,United States of America|United Kingdom,Dune Entertainment|Lightstorm Entertainment|20...,English|Español
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,245000000,140607,[US],en,Thirty years after defeating the Galactic Empi...,12.7841,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,2015-12-15,2068223624,...,Released,Every generation has a story.,Star Wars: The Force Awakens,7.262,19665,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.|Bad Robot,English
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,300000000,299536,[US],en,As the Avengers and their allies have continue...,32.6907,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,2018-04-25,2052415039,...,Released,Destiny arrives all the same.,Avengers: Infinity War,8.236,30386,The Avengers Collection,Adventure|Action|Science Fiction,United States of America,Marvel Studios,English|
4,/sCzcYW9h55WcesOqA12cgEr9Exw.jpg,200000000,597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,31.6333,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,1997-11-18,2264162353,...,Released,Nothing on Earth could come between them.,Titanic,7.905,25865,None,Drama|Romance,United States of America,Paramount Pictures|20th Century Fox|Lightstorm...,English|Français|Deutsch|svenska|Italiano|Pусский
5,/aIGIYJTyOkEVUmEd3z5x6diYsFx.jpg,150000000,135397,[US],en,Twenty-two years after the events of Jurassic ...,19.5099,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,2015-06-06,1671537444,...,Released,The park is open.,Jurassic World,6.700,20623,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,260000000,420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",22.2842,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,2019-07-12,1662020819,...,Released,The king has returned.,The Lion King,7.109,10301,The Lion King (Reboot) Collection,Adventure|Drama|Family|Animation,United States of America,Walt Disney Pictures|Fairview Entertainment,English
7,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,220000000,24428,[US],en,When an unexpected enemy emerges and threatens...,33.8215,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,2012-04-25,1518815515,...,Released,Some assembly required.,The Avengers,7.734,31505,The Avengers Collection,Science Fiction|Action|Adventure,United States of America,Marvel Studios,English|हिन्दी|Pусский
8,/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg,190000000,168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,14.2561,/wurKlC3VKUgcfsn0K51MJYEleS2.jpg,2015-04-01,1515400000,...,Released,Vengeance hits home.,Furious 7,7.225,10760,The Fast and the Furious Collection,Action|Thriller|Crime,United States of America,Original Film|One Race|Universal Pictures,العربية|English|Español|ภาษาไทย
9,/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg,365000000,99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,17.2051,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,2015-04-22,1405403694,...,Released,A new age has come.,Avengers: Age of Ultron,7.271,23345,The Avengers Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English
10,/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg,200000000,284054,[US],en,"King T'Challa returns home to the reclusive, t...",18.2929,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,2018-02-13,1349926083,...,Released,Long live the king.,Black Panther,7.400,22488,Black Panther Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English|한국어/조선말|Kiswahili|
11,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,125000000,12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",18.2595,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,2011-07-12,1341511219,...,Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.087,20935,Harry Potter Collection,Fantasy|Adventure,United Kingdom|United States of America,Warner Bros. Pictures|Heyday Films,English
12,/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg,200000000,181808,[US],en,Rey develops her newly discovered abilities wi...,13.8661,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,2017-12-13,1332698830,...,Released,Darkness rises...and light to meet it.,Star Wars: The Last Jedi,6.779,15532,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.,English
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,150000000,330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",11.1016,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,2019-11-20,1453683476,...,Released,The past is not what it seems.,Frozen II,7.250,9867,Frozen Collection,Family|Animation|Adventure|Comedy|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,170000000,351286,[US],en,Three years after Jurassic World was destroyed...,14.0844,/270MrJNqJovumHXGE6SSt0zwUIF.jpg,2018-06-06,1310466296,...,Released,The park is gone.,Jurassic World: Fallen Kingdom,6.538,12004,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English|Pусский
15,/u2bZhH3nTf0So0UIC1QxAqBvC07.jpg,150000000,109445,[US],en,Young princess Anna of Arendelle dreams about ...,20.7782,/m4uhSpErBKprhsclr0zynTYdupb.jpg,2013-11-20,1274219009,...,Released,Only the act of true love will thaw a frozen h...,Frozen,7.200,16777,Frozen Collection,Animation|Family|Adventure|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,160000000,321612,[US],en,A live-action adaptation of Disney's version o...,17.1086,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,2017-03-16,1266115964,...,Released,Be our guest.,Beauty and the Beast,6.971,15584,None,Family|Fantasy|Romance,United States of America,Walt Disney Pictures|Mandeville Films,English|Français
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,200000000,260513,[US],en,Elastigirl springs into action to save the day...,9.8992,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,2018-06-14,1242805359,...,Released,"It's been too long, dahlings.",Incredibles 2,7.454,13021,The Incredibles Collection,Action|Adventure|Animation|Family,United States of America,Walt Disney Pictures|Pixar,English

#### 6. Replace unrealistic values:

#####  Budget/Revenue/Runtime = 0 → Replace with NaN or infer from similar movies.

In [14]:
movie_df['budget']=movie_df['budget'].replace(0, np.nan)
movie_df['revenue']=movie_df['revenue'].replace(0, np.nan)
movie_df['runtime']=movie_df['runtime'].replace(0, np.nan)

##### Convert 'budget' and 'revenue' to million USD.

In [15]:
movie_df['revenue'] = movie_df['revenue'] / 1000000
movie_df['budget'] = movie_df['budget'] / 1000000
movie_df=movie_df.rename(columns={'revenue': 'revenue_musd', 'budget': 'budget_musd'})

In [16]:
movie_df

,backdrop_path,budget_musd,id,origin_country,original_language,overview,popularity,poster_path,release_date,revenue_musd,...,status,tagline,title,vote_average,vote_count,belongs_to_collection,genres,production_countries,production_companies,spoken_languages
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,356.0,299534,[US],en,After the devastating events of Avengers: Infi...,22.2597,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,2019-04-24,2799.439100,...,Released,Avenge the fallen.,Avengers: Endgame,8.238,26206,The Avengers Collection,Adventure|Science Fiction|Action,United States of America,Marvel Studios,English|日本語|
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,237.0,19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",31.3525,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,2009-12-15,2923.706026,...,Released,Enter the world of Pandora.,Avatar,7.588,32112,Avatar Collection,Action|Adventure|Fantasy|Science Fiction,United States of America|United Kingdom,Dune Entertainment|Lightstorm Entertainment|20...,English|Español
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,245.0,140607,[US],en,Thirty years after defeating the Galactic Empi...,12.7841,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,2015-12-15,2068.223624,...,Released,Every generation has a story.,Star Wars: The Force Awakens,7.262,19665,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.|Bad Robot,English
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,300.0,299536,[US],en,As the Avengers and their allies have continue...,32.6907,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,2018-04-25,2052.415039,...,Released,Destiny arrives all the same.,Avengers: Infinity War,8.236,30386,The Avengers Collection,Adventure|Action|Science Fiction,United States of America,Marvel Studios,English|
4,/sCzcYW9h55WcesOqA12cgEr9Exw.jpg,200.0,597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,31.6333,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,1997-11-18,2264.162353,...,Released,Nothing on Earth could come between them.,Titanic,7.905,25865,None,Drama|Romance,United States of America,Paramount Pictures|20th Century Fox|Lightstorm...,English|Français|Deutsch|svenska|Italiano|Pусский
5,/aIGIYJTyOkEVUmEd3z5x6diYsFx.jpg,150.0,135397,[US],en,Twenty-two years after the events of Jurassic ...,19.5099,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,2015-06-06,1671.537444,...,Released,The park is open.,Jurassic World,6.700,20623,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,260.0,420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",22.2842,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,2019-07-12,1662.020819,...,Released,The king has returned.,The Lion King,7.109,10301,The Lion King (Reboot) Collection,Adventure|Drama|Family|Animation,United States of America,Walt Disney Pictures|Fairview Entertainment,English
7,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,220.0,24428,[US],en,When an unexpected enemy emerges and threatens...,33.8215,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,2012-04-25,1518.815515,...,Released,Some assembly required.,The Avengers,7.734,31505,The Avengers Collection,Science Fiction|Action|Adventure,United States of America,Marvel Studios,English|हिन्दी|Pусский
8,/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg,190.0,168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,14.2561,/wurKlC3VKUgcfsn0K51MJYEleS2.jpg,2015-04-01,1515.400000,...,Released,Vengeance hits home.,Furious 7,7.225,10760,The Fast and the Furious Collection,Action|Thriller|Crime,United States of America,Original Film|One Race|Universal Pictures,العربية|English|Español|ภาษาไทย
9,/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg,365.0,99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,17.2051,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,2015-04-22,1405.403694,...,Released,A new age has come.,Avengers: Age of Ultron,7.271,23345,The Avengers Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English
10,/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg,200.0,284054,[US],en,"King T'Challa returns home to the reclusive, t...",18.2929,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,2018-02-13,1349.926083,...,Released,Long live the king.,Black Panther,7.400,22488,Black Panther Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English|한국어/조선말|Kiswahili|
11,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,125.0,12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",18.2595,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,2011-07-12,1341.511219,...,Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.087,20935,Harry Potter Collection,Fantasy|Adventure,United Kingdom|United States of America,Warner Bros. Pictures|Heyday Films,English
12,/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg,200.0,181808,[US],en,Rey develops her newly discovered abilities wi...,13.8661,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,2017-12-13,1332.698830,...,Released,Darkness rises...and light to meet it.,Star Wars: The Last Jedi,6.779,15532,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.,English
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,150.0,330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",11.1016,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,2019-11-20,1453.683476,...,Released,The past is not what it seems.,Frozen II,7.250,9867,Frozen Collection,Family|Animation|Adventure|Comedy|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,170.0,351286,[US],en,Three years after Jurassic World was destroyed...,14.0844,/270MrJNqJovumHXGE6SSt0zwUIF.jpg,2018-06-06,1310.466296,...,Released,The park is gone.,Jurassic World: Fallen Kingdom,6.538,12004,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English|Pусский
15,/u2bZhH3nTf0So0UIC1QxAqBvC07.jpg,150.0,109445,[US],en,Young princess Anna of Arendelle dreams about ...,20.7782,/m4uhSpErBKprhsclr0zynTYdupb.jpg,2013-11-20,1274.219009,...,Released,Only the act of true love will thaw a frozen h...,Frozen,7.200,16777,Frozen Collection,Animation|Family|Adventure|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,160.0,321612,[US],en,A live-action adaptation of Disney's version o...,17.1086,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,2017-03-16,1266.115964,...,Released,Be our guest.,Beauty and the Beast,6.971,15584,None,Family|Fantasy|Romance,United States of America,Walt Disney Pictures|Mandeville Films,English|Français
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,200.0,260513,[US],en,Elastigirl springs into action to save the day...,9.8992,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,2018-06-14,1242.805359,...,Released,"It's been too long, dahlings.",Incredibles 2,7.454,13021,The Incredibles Collection,Action|Adventure|Animation|Family,United States of America,Walt Disney Pictures|Pixar,English

##### Movies with vote_count = 0 → Analyze their vote_average and adjusting with weighted average of value_count.

In [17]:
movie_df.loc[movie_df['vote_count'] == 0, 'vote_count'] = movie_df[movie_df['vote_count'] > 0]['vote_count'].mean()
movie_df[['overview', 'tagline']] = movie_df[['overview', 'tagline']].replace(['No Data', 'Null','null','Unknown', 'N/A',-1,''], np.nan)
movie_df

,backdrop_path,budget_musd,id,origin_country,original_language,overview,popularity,poster_path,release_date,revenue_musd,...,status,tagline,title,vote_average,vote_count,belongs_to_collection,genres,production_countries,production_companies,spoken_languages
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,356.0,299534,[US],en,After the devastating events of Avengers: Infi...,22.2597,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,2019-04-24,2799.439100,...,Released,Avenge the fallen.,Avengers: Endgame,8.238,26206,The Avengers Collection,Adventure|Science Fiction|Action,United States of America,Marvel Studios,English|日本語|
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,237.0,19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",31.3525,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,2009-12-15,2923.706026,...,Released,Enter the world of Pandora.,Avatar,7.588,32112,Avatar Collection,Action|Adventure|Fantasy|Science Fiction,United States of America|United Kingdom,Dune Entertainment|Lightstorm Entertainment|20...,English|Español
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,245.0,140607,[US],en,Thirty years after defeating the Galactic Empi...,12.7841,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,2015-12-15,2068.223624,...,Released,Every generation has a story.,Star Wars: The Force Awakens,7.262,19665,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.|Bad Robot,English
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,300.0,299536,[US],en,As the Avengers and their allies have continue...,32.6907,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,2018-04-25,2052.415039,...,Released,Destiny arrives all the same.,Avengers: Infinity War,8.236,30386,The Avengers Collection,Adventure|Action|Science Fiction,United States of America,Marvel Studios,English|
4,/sCzcYW9h55WcesOqA12cgEr9Exw.jpg,200.0,597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,31.6333,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,1997-11-18,2264.162353,...,Released,Nothing on Earth could come between them.,Titanic,7.905,25865,None,Drama|Romance,United States of America,Paramount Pictures|20th Century Fox|Lightstorm...,English|Français|Deutsch|svenska|Italiano|Pусский
5,/aIGIYJTyOkEVUmEd3z5x6diYsFx.jpg,150.0,135397,[US],en,Twenty-two years after the events of Jurassic ...,19.5099,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,2015-06-06,1671.537444,...,Released,The park is open.,Jurassic World,6.700,20623,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,260.0,420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",22.2842,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,2019-07-12,1662.020819,...,Released,The king has returned.,The Lion King,7.109,10301,The Lion King (Reboot) Collection,Adventure|Drama|Family|Animation,United States of America,Walt Disney Pictures|Fairview Entertainment,English
7,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,220.0,24428,[US],en,When an unexpected enemy emerges and threatens...,33.8215,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,2012-04-25,1518.815515,...,Released,Some assembly required.,The Avengers,7.734,31505,The Avengers Collection,Science Fiction|Action|Adventure,United States of America,Marvel Studios,English|हिन्दी|Pусский
8,/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg,190.0,168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,14.2561,/wurKlC3VKUgcfsn0K51MJYEleS2.jpg,2015-04-01,1515.400000,...,Released,Vengeance hits home.,Furious 7,7.225,10760,The Fast and the Furious Collection,Action|Thriller|Crime,United States of America,Original Film|One Race|Universal Pictures,العربية|English|Español|ภาษาไทย
9,/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg,365.0,99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,17.2051,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,2015-04-22,1405.403694,...,Released,A new age has come.,Avengers: Age of Ultron,7.271,23345,The Avengers Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English
10,/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg,200.0,284054,[US],en,"King T'Challa returns home to the reclusive, t...",18.2929,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,2018-02-13,1349.926083,...,Released,Long live the king.,Black Panther,7.400,22488,Black Panther Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English|한국어/조선말|Kiswahili|
11,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,125.0,12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",18.2595,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,2011-07-12,1341.511219,...,Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.087,20935,Harry Potter Collection,Fantasy|Adventure,United Kingdom|United States of America,Warner Bros. Pictures|Heyday Films,English
12,/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg,200.0,181808,[US],en,Rey develops her newly discovered abilities wi...,13.8661,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,2017-12-13,1332.698830,...,Released,Darkness rises...and light to meet it.,Star Wars: The Last Jedi,6.779,15532,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.,English
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,150.0,330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",11.1016,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,2019-11-20,1453.683476,...,Released,The past is not what it seems.,Frozen II,7.250,9867,Frozen Collection,Family|Animation|Adventure|Comedy|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,170.0,351286,[US],en,Three years after Jurassic World was destroyed...,14.0844,/270MrJNqJovumHXGE6SSt0zwUIF.jpg,2018-06-06,1310.466296,...,Released,The park is gone.,Jurassic World: Fallen Kingdom,6.538,12004,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English|Pусский
15,/u2bZhH3nTf0So0UIC1QxAqBvC07.jpg,150.0,109445,[US],en,Young princess Anna of Arendelle dreams about ...,20.7782,/m4uhSpErBKprhsclr0zynTYdupb.jpg,2013-11-20,1274.219009,...,Released,Only the act of true love will thaw a frozen h...,Frozen,7.200,16777,Frozen Collection,Animation|Family|Adventure|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,160.0,321612,[US],en,A live-action adaptation of Disney's version o...,17.1086,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,2017-03-16,1266.115964,...,Released,Be our guest.,Beauty and the Beast,6.971,15584,None,Family|Fantasy|Romance,United States of America,Walt Disney Pictures|Mandeville Films,English|Français
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,200.0,260513,[US],en,Elastigirl springs into action to save the day...,9.8992,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,2018-06-14,1242.805359,...,Released,"It's been too long, dahlings.",Incredibles 2,7.454,13021,The Incredibles Collection,Action|Adventure|Animation|Family,United States of America,Walt Disney Pictures|Pixar,English

#### 7. Remove duplicates and drop rows with unknown 'id' or 'title'.

In [18]:
# Extract the first element from lists in the 'origin_country' column
movie_df['origin_country'] = movie_df['origin_country'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else np.nan)
movie_df

,backdrop_path,budget_musd,id,origin_country,original_language,overview,popularity,poster_path,release_date,revenue_musd,...,status,tagline,title,vote_average,vote_count,belongs_to_collection,genres,production_countries,production_companies,spoken_languages
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,356.0,299534,US,en,After the devastating events of Avengers: Infi...,22.2597,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,2019-04-24,2799.439100,...,Released,Avenge the fallen.,Avengers: Endgame,8.238,26206,The Avengers Collection,Adventure|Science Fiction|Action,United States of America,Marvel Studios,English|日本語|
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,237.0,19995,US,en,"In the 22nd century, a paraplegic Marine is di...",31.3525,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,2009-12-15,2923.706026,...,Released,Enter the world of Pandora.,Avatar,7.588,32112,Avatar Collection,Action|Adventure|Fantasy|Science Fiction,United States of America|United Kingdom,Dune Entertainment|Lightstorm Entertainment|20...,English|Español
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,245.0,140607,US,en,Thirty years after defeating the Galactic Empi...,12.7841,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,2015-12-15,2068.223624,...,Released,Every generation has a story.,Star Wars: The Force Awakens,7.262,19665,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.|Bad Robot,English
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,300.0,299536,US,en,As the Avengers and their allies have continue...,32.6907,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,2018-04-25,2052.415039,...,Released,Destiny arrives all the same.,Avengers: Infinity War,8.236,30386,The Avengers Collection,Adventure|Action|Science Fiction,United States of America,Marvel Studios,English|
4,/sCzcYW9h55WcesOqA12cgEr9Exw.jpg,200.0,597,US,en,101-year-old Rose DeWitt Bukater tells the sto...,31.6333,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,1997-11-18,2264.162353,...,Released,Nothing on Earth could come between them.,Titanic,7.905,25865,None,Drama|Romance,United States of America,Paramount Pictures|20th Century Fox|Lightstorm...,English|Français|Deutsch|svenska|Italiano|Pусский
5,/aIGIYJTyOkEVUmEd3z5x6diYsFx.jpg,150.0,135397,US,en,Twenty-two years after the events of Jurassic ...,19.5099,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,2015-06-06,1671.537444,...,Released,The park is open.,Jurassic World,6.700,20623,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,260.0,420818,US,en,"Simba idolizes his father, King Mufasa, and ta...",22.2842,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,2019-07-12,1662.020819,...,Released,The king has returned.,The Lion King,7.109,10301,The Lion King (Reboot) Collection,Adventure|Drama|Family|Animation,United States of America,Walt Disney Pictures|Fairview Entertainment,English
7,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,220.0,24428,US,en,When an unexpected enemy emerges and threatens...,33.8215,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,2012-04-25,1518.815515,...,Released,Some assembly required.,The Avengers,7.734,31505,The Avengers Collection,Science Fiction|Action|Adventure,United States of America,Marvel Studios,English|हिन्दी|Pусский
8,/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg,190.0,168259,US,en,Deckard Shaw seeks revenge against Dominic Tor...,14.2561,/wurKlC3VKUgcfsn0K51MJYEleS2.jpg,2015-04-01,1515.400000,...,Released,Vengeance hits home.,Furious 7,7.225,10760,The Fast and the Furious Collection,Action|Thriller|Crime,United States of America,Original Film|One Race|Universal Pictures,العربية|English|Español|ภาษาไทย
9,/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg,365.0,99861,US,en,When Tony Stark tries to jumpstart a dormant p...,17.2051,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,2015-04-22,1405.403694,...,Released,A new age has come.,Avengers: Age of Ultron,7.271,23345,The Avengers Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English
10,/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg,200.0,284054,US,en,"King T'Challa returns home to the reclusive, t...",18.2929,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,2018-02-13,1349.926083,...,Released,Long live the king.,Black Panther,7.400,22488,Black Panther Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English|한국어/조선말|Kiswahili|
11,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,125.0,12445,GB,en,"Harry, Ron and Hermione continue their quest t...",18.2595,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,2011-07-12,1341.511219,...,Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.087,20935,Harry Potter Collection,Fantasy|Adventure,United Kingdom|United States of America,Warner Bros. Pictures|Heyday Films,English
12,/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg,200.0,181808,US,en,Rey develops her newly discovered abilities wi...,13.8661,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,2017-12-13,1332.698830,...,Released,Darkness rises...and light to meet it.,Star Wars: The Last Jedi,6.779,15532,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.,English
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,150.0,330457,US,en,"Elsa, Anna, Kristoff and Olaf head far into th...",11.1016,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,2019-11-20,1453.683476,...,Released,The past is not what it seems.,Frozen II,7.250,9867,Frozen Collection,Family|Animation|Adventure|Comedy|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,170.0,351286,US,en,Three years after Jurassic World was destroyed...,14.0844,/270MrJNqJovumHXGE6SSt0zwUIF.jpg,2018-06-06,1310.466296,...,Released,The park is gone.,Jurassic World: Fallen Kingdom,6.538,12004,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English|Pусский
15,/u2bZhH3nTf0So0UIC1QxAqBvC07.jpg,150.0,109445,US,en,Young princess Anna of Arendelle dreams about ...,20.7782,/m4uhSpErBKprhsclr0zynTYdupb.jpg,2013-11-20,1274.219009,...,Released,Only the act of true love will thaw a frozen h...,Frozen,7.200,16777,Frozen Collection,Animation|Family|Adventure|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,160.0,321612,US,en,A live-action adaptation of Disney's version o...,17.1086,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,2017-03-16,1266.115964,...,Released,Be our guest.,Beauty and the Beast,6.971,15584,None,Family|Fantasy|Romance,United States of America,Walt Disney Pictures|Mandeville Films,English|Français
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,200.0,260513,US,en,Elastigirl springs into action to save the day...,9.8992,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,2018-06-14,1242.805359,...,Released,"It's been too long, dahlings.",Incredibles 2,7.454,13021,The Incredibles Collection,Action|Adventure|Animation|Family,United States of America,Walt Disney Pictures|Pixar,English

In [19]:
# Remove duplicates from the DataFrame
movie_df = movie_df.drop_duplicates()
movie_df = movie_df.dropna(subset=['id', 'title'])

#### 8. Keep only rows where at least 10 columns have non-NaN values

In [20]:
movie_df = movie_df.dropna(thresh=10)
movie_df

,backdrop_path,budget_musd,id,origin_country,original_language,overview,popularity,poster_path,release_date,revenue_musd,...,status,tagline,title,vote_average,vote_count,belongs_to_collection,genres,production_countries,production_companies,spoken_languages
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,356.0,299534,US,en,After the devastating events of Avengers: Infi...,22.2597,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,2019-04-24,2799.439100,...,Released,Avenge the fallen.,Avengers: Endgame,8.238,26206,The Avengers Collection,Adventure|Science Fiction|Action,United States of America,Marvel Studios,English|日本語|
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,237.0,19995,US,en,"In the 22nd century, a paraplegic Marine is di...",31.3525,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,2009-12-15,2923.706026,...,Released,Enter the world of Pandora.,Avatar,7.588,32112,Avatar Collection,Action|Adventure|Fantasy|Science Fiction,United States of America|United Kingdom,Dune Entertainment|Lightstorm Entertainment|20...,English|Español
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,245.0,140607,US,en,Thirty years after defeating the Galactic Empi...,12.7841,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,2015-12-15,2068.223624,...,Released,Every generation has a story.,Star Wars: The Force Awakens,7.262,19665,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.|Bad Robot,English
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,300.0,299536,US,en,As the Avengers and their allies have continue...,32.6907,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,2018-04-25,2052.415039,...,Released,Destiny arrives all the same.,Avengers: Infinity War,8.236,30386,The Avengers Collection,Adventure|Action|Science Fiction,United States of America,Marvel Studios,English|
4,/sCzcYW9h55WcesOqA12cgEr9Exw.jpg,200.0,597,US,en,101-year-old Rose DeWitt Bukater tells the sto...,31.6333,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,1997-11-18,2264.162353,...,Released,Nothing on Earth could come between them.,Titanic,7.905,25865,None,Drama|Romance,United States of America,Paramount Pictures|20th Century Fox|Lightstorm...,English|Français|Deutsch|svenska|Italiano|Pусский
5,/aIGIYJTyOkEVUmEd3z5x6diYsFx.jpg,150.0,135397,US,en,Twenty-two years after the events of Jurassic ...,19.5099,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,2015-06-06,1671.537444,...,Released,The park is open.,Jurassic World,6.700,20623,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,260.0,420818,US,en,"Simba idolizes his father, King Mufasa, and ta...",22.2842,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,2019-07-12,1662.020819,...,Released,The king has returned.,The Lion King,7.109,10301,The Lion King (Reboot) Collection,Adventure|Drama|Family|Animation,United States of America,Walt Disney Pictures|Fairview Entertainment,English
7,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,220.0,24428,US,en,When an unexpected enemy emerges and threatens...,33.8215,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,2012-04-25,1518.815515,...,Released,Some assembly required.,The Avengers,7.734,31505,The Avengers Collection,Science Fiction|Action|Adventure,United States of America,Marvel Studios,English|हिन्दी|Pусский
8,/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg,190.0,168259,US,en,Deckard Shaw seeks revenge against Dominic Tor...,14.2561,/wurKlC3VKUgcfsn0K51MJYEleS2.jpg,2015-04-01,1515.400000,...,Released,Vengeance hits home.,Furious 7,7.225,10760,The Fast and the Furious Collection,Action|Thriller|Crime,United States of America,Original Film|One Race|Universal Pictures,العربية|English|Español|ภาษาไทย
9,/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg,365.0,99861,US,en,When Tony Stark tries to jumpstart a dormant p...,17.2051,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,2015-04-22,1405.403694,...,Released,A new age has come.,Avengers: Age of Ultron,7.271,23345,The Avengers Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English
10,/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg,200.0,284054,US,en,"King T'Challa returns home to the reclusive, t...",18.2929,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,2018-02-13,1349.926083,...,Released,Long live the king.,Black Panther,7.400,22488,Black Panther Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English|한국어/조선말|Kiswahili|
11,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,125.0,12445,GB,en,"Harry, Ron and Hermione continue their quest t...",18.2595,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,2011-07-12,1341.511219,...,Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.087,20935,Harry Potter Collection,Fantasy|Adventure,United Kingdom|United States of America,Warner Bros. Pictures|Heyday Films,English
12,/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg,200.0,181808,US,en,Rey develops her newly discovered abilities wi...,13.8661,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,2017-12-13,1332.698830,...,Released,Darkness rises...and light to meet it.,Star Wars: The Last Jedi,6.779,15532,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.,English
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,150.0,330457,US,en,"Elsa, Anna, Kristoff and Olaf head far into th...",11.1016,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,2019-11-20,1453.683476,...,Released,The past is not what it seems.,Frozen II,7.250,9867,Frozen Collection,Family|Animation|Adventure|Comedy|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,170.0,351286,US,en,Three years after Jurassic World was destroyed...,14.0844,/270MrJNqJovumHXGE6SSt0zwUIF.jpg,2018-06-06,1310.466296,...,Released,The park is gone.,Jurassic World: Fallen Kingdom,6.538,12004,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English|Pусский
15,/u2bZhH3nTf0So0UIC1QxAqBvC07.jpg,150.0,109445,US,en,Young princess Anna of Arendelle dreams about ...,20.7782,/m4uhSpErBKprhsclr0zynTYdupb.jpg,2013-11-20,1274.219009,...,Released,Only the act of true love will thaw a frozen h...,Frozen,7.200,16777,Frozen Collection,Animation|Family|Adventure|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,160.0,321612,US,en,A live-action adaptation of Disney's version o...,17.1086,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,2017-03-16,1266.115964,...,Released,Be our guest.,Beauty and the Beast,6.971,15584,None,Family|Fantasy|Romance,United States of America,Walt Disney Pictures|Mandeville Films,English|Français
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,200.0,260513,US,en,Elastigirl springs into action to save the day...,9.8992,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,2018-06-14,1242.805359,...,Released,"It's been too long, dahlings.",Incredibles 2,7.454,13021,The Incredibles Collection,Action|Adventure|Animation|Family,United States of America,Walt Disney Pictures|Pixar,English

In [21]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   backdrop_path          18 non-null     object
 1   budget_musd            18 non-null     float64
 2   id                     18 non-null     int64
 3   origin_country         18 non-null     object
 4   original_language      18 non-null     object
 5   overview               18 non-null     object
 6   popularity             18 non-null     float64
 7   poster_path            18 non-null     object
 8   release_date           18 non-null     datetime64[ns]
 9   revenue_musd           18 non-null     float64
 10  runtime                18 non-null     int64
 11  status                 18 non-null     object
 12  tagline                18 non-null     object
 13  title                  18 non-null     object
 14  vote_average           18 non-null     float64
 15  vote_count             18 non-null     int64
 16  belongs_to_collection  16 non-null     object
 17  genres                 18 non-null     object
 18  production_countries   18 non-null     object
 19  production_companies   18 non-null     object
 20  spoken_languages       18 non-null     object
dtypes: datetime64[ns](1), float64(4), int64(3), object(13)
memory usage: 3.1+ KB

#### 9. Filter to include only 'Released' movies, then drop 'status'.

In [22]:
movie_df=movie_df.loc[movie_df['status'] == 'Released']
movie_df=movie_df.drop(columns=['status'])
movie_df

,backdrop_path,budget_musd,id,origin_country,original_language,overview,popularity,poster_path,release_date,revenue_musd,runtime,tagline,title,vote_average,vote_count,belongs_to_collection,genres,production_countries,production_companies,spoken_languages
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,356.0,299534,US,en,After the devastating events of Avengers: Infi...,22.2597,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,2019-04-24,2799.439100,181,Avenge the fallen.,Avengers: Endgame,8.238,26206,The Avengers Collection,Adventure|Science Fiction|Action,United States of America,Marvel Studios,English|日本語|
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,237.0,19995,US,en,"In the 22nd century, a paraplegic Marine is di...",31.3525,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,2009-12-15,2923.706026,162,Enter the world of Pandora.,Avatar,7.588,32112,Avatar Collection,Action|Adventure|Fantasy|Science Fiction,United States of America|United Kingdom,Dune Entertainment|Lightstorm Entertainment|20...,English|Español
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,245.0,140607,US,en,Thirty years after defeating the Galactic Empi...,12.7841,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,2015-12-15,2068.223624,136,Every generation has a story.,Star Wars: The Force Awakens,7.262,19665,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.|Bad Robot,English
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,300.0,299536,US,en,As the Avengers and their allies have continue...,32.6907,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,2018-04-25,2052.415039,149,Destiny arrives all the same.,Avengers: Infinity War,8.236,30386,The Avengers Collection,Adventure|Action|Science Fiction,United States of America,Marvel Studios,English|
4,/sCzcYW9h55WcesOqA12cgEr9Exw.jpg,200.0,597,US,en,101-year-old Rose DeWitt Bukater tells the sto...,31.6333,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,1997-11-18,2264.162353,194,Nothing on Earth could come between them.,Titanic,7.905,25865,None,Drama|Romance,United States of America,Paramount Pictures|20th Century Fox|Lightstorm...,English|Français|Deutsch|svenska|Italiano|Pусский
5,/aIGIYJTyOkEVUmEd3z5x6diYsFx.jpg,150.0,135397,US,en,Twenty-two years after the events of Jurassic ...,19.5099,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,2015-06-06,1671.537444,124,The park is open.,Jurassic World,6.700,20623,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,260.0,420818,US,en,"Simba idolizes his father, King Mufasa, and ta...",22.2842,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,2019-07-12,1662.020819,118,The king has returned.,The Lion King,7.109,10301,The Lion King (Reboot) Collection,Adventure|Drama|Family|Animation,United States of America,Walt Disney Pictures|Fairview Entertainment,English
7,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,220.0,24428,US,en,When an unexpected enemy emerges and threatens...,33.8215,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,2012-04-25,1518.815515,143,Some assembly required.,The Avengers,7.734,31505,The Avengers Collection,Science Fiction|Action|Adventure,United States of America,Marvel Studios,English|हिन्दी|Pусский
8,/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg,190.0,168259,US,en,Deckard Shaw seeks revenge against Dominic Tor...,14.2561,/wurKlC3VKUgcfsn0K51MJYEleS2.jpg,2015-04-01,1515.400000,137,Vengeance hits home.,Furious 7,7.225,10760,The Fast and the Furious Collection,Action|Thriller|Crime,United States of America,Original Film|One Race|Universal Pictures,العربية|English|Español|ภาษาไทย
9,/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg,365.0,99861,US,en,When Tony Stark tries to jumpstart a dormant p...,17.2051,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,2015-04-22,1405.403694,141,A new age has come.,Avengers: Age of Ultron,7.271,23345,The Avengers Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English
10,/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg,200.0,284054,US,en,"King T'Challa returns home to the reclusive, t...",18.2929,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,2018-02-13,1349.926083,135,Long live the king.,Black Panther,7.400,22488,Black Panther Collection,Action|Adventure|Science Fiction,United States of America,Marvel Studios,English|한국어/조선말|Kiswahili|
11,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,125.0,12445,GB,en,"Harry, Ron and Hermione continue their quest t...",18.2595,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,2011-07-12,1341.511219,130,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.087,20935,Harry Potter Collection,Fantasy|Adventure,United Kingdom|United States of America,Warner Bros. Pictures|Heyday Films,English
12,/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg,200.0,181808,US,en,Rey develops her newly discovered abilities wi...,13.8661,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,2017-12-13,1332.698830,152,Darkness rises...and light to meet it.,Star Wars: The Last Jedi,6.779,15532,Star Wars Collection,Adventure|Action|Science Fiction,United States of America,Lucasfilm Ltd.,English
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,150.0,330457,US,en,"Elsa, Anna, Kristoff and Olaf head far into th...",11.1016,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,2019-11-20,1453.683476,103,The past is not what it seems.,Frozen II,7.250,9867,Frozen Collection,Family|Animation|Adventure|Comedy|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,170.0,351286,US,en,Three years after Jurassic World was destroyed...,14.0844,/270MrJNqJovumHXGE6SSt0zwUIF.jpg,2018-06-06,1310.466296,129,The park is gone.,Jurassic World: Fallen Kingdom,6.538,12004,Jurassic Park Collection,Action|Adventure|Science Fiction|Thriller,United States of America,Amblin Entertainment|Universal Pictures,English|Pусский
15,/u2bZhH3nTf0So0UIC1QxAqBvC07.jpg,150.0,109445,US,en,Young princess Anna of Arendelle dreams about ...,20.7782,/m4uhSpErBKprhsclr0zynTYdupb.jpg,2013-11-20,1274.219009,102,Only the act of true love will thaw a frozen h...,Frozen,7.200,16777,Frozen Collection,Animation|Family|Adventure|Fantasy,United States of America,Walt Disney Pictures|Walt Disney Animation Stu...,English
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,160.0,321612,US,en,A live-action adaptation of Disney's version o...,17.1086,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,2017-03-16,1266.115964,129,Be our guest.,Beauty and the Beast,6.971,15584,None,Family|Fantasy|Romance,United States of America,Walt Disney Pictures|Mandeville Films,English|Français
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,200.0,260513,US,en,Elastigirl springs into action to save the day...,9.8992,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,2018-06-14,1242.805359,118,"It's been too long, dahlings.",Incredibles 2,7.454,13021,The Incredibles Collection,Action|Adventure|Animation|Family,United States of America,Walt Disney Pictures|Pixar,English